
services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest # remember to change this if you're using rpi
    profiles: ["traefik", "core", "all"]

    networks:
      - proxy
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "85:80/tcp"
    #- "443:443/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'password'
      PIHOLE_DNS_: '172.23.0.8#5053'
    volumes:
      - '/apps/pihole/etc-pihole/:/etc/pihole/'
      - '/apps/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped

    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`pihole.nanaoware.online`) || Host(`www.pihole.nanaoware.online`)
      - traefik.http.services.pihole.loadbalancer.server.port=80
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.mypihole.middlewares=mywwwredirect
      - traefik.http.routers.mypihole.middlewares=dashboard
      - traefik.http.routers.mypihole.service=api@internal
      - traefik.http.routers.mypihole.tls=true
      - traefik.http.routers.mypihole.tls.certresolver=le
ubound:
    container_name: unbound
    image: mvance/unbound:latest # remember to change this if you're using rpi
    networks:
      - proxy
    volumes:
      - /apps/pihole/unbound:/opt/unbound/etc/unbound
    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
    healthcheck:
      test: ["NONE"]
    restart: unless-stopped