version: "3.9"
services:
  changedetection:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: changedetection
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/changedetection/config:/config
    ports:
      - 5000:5000
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.changedetection.rule=Host(`cd.nanaoware.online`) || Host(`www.cd.nanaoware.online`)
      - traefik.http.services.changedetection.loadbalancer.server.port=5000
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.mychangedetection.middlewares=mywwwredirect
      - traefik.http.routers.mychangedetection.middlewares=myauth
      - traefik.http.routers.mychangedetection.service=api@internal

networks:
  proxy:
    external: true