
services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - data:/data
    #ports:
    #  - 3000:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      OPENAI_API_KEY: OPENAI_API_KEY
      DATA_DIR: /data
    networks:
      - traefik
      - hoarder
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.hoarder-http.entrypoints=http"
      - "traefik.http.routers.hoarder-http.middlewares=redir-https"
      - "traefik.http.routers.hoarder-http.rule=Host(`hoarder.linuxpad.blog`)"
      - "traefik.http.routers.hoarder-http.service=noop@internal"
      - "traefik.http.routers.hoarder-https.entrypoints=https"
      - "traefik.http.routers.hoarder-https.tls=true"
      - "traefik.http.routers.hoarder-https.middlewares=gzip"
      - "traefik.http.routers.hoarder-https.rule=Host(`hoarder.linuxpad.blog`)"
      - "traefik.http.services.hoarder-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.hoarder-backend.loadbalancer.server.port=3000"
      - "traefik.http.routers.hoarder-https.middlewares=authelia@docker"
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - hoarder
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data
    networks:
      - hoarder

volumes:
  meilisearch:
  data:

networks:
  traefik:
    external: true
  hoarder: