services:
  client:
    image: bluewaveuptime/uptime_client:latest
    restart: always
    environment:
      UPTIME_APP_API_BASE_URL: "https://checkmate.jimsgarage.co.uk/api/v1"
    #ports:
    #  - "80:80"
    #  - "443:443"
    depends_on:
      - server
    networks:
      - traefik
      - checkmate
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.checkmate-http.entrypoints=http"
      - "traefik.http.routers.checkmate-http.middlewares=redir-https"
      - "traefik.http.routers.checkmate-http.rule=Host(`checkmate.linuxpad.blog`)"
      - "traefik.http.routers.checkmate-http.service=noop@internal"
      - "traefik.http.routers.checkmate-https.entrypoints=https"
      - "traefik.http.routers.checkmate-https.tls=true"
      - "traefik.http.routers.checkmate-https.middlewares=gzip"
      - "traefik.http.routers.checkmate-https.rule=Host(`checkmate.linuxpad.blog`)"
      - "traefik.http.services.checkmate-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.checkmate-backend.loadbalancer.server.port=80"
      - "traefik.http.routers.checkmate-https.middlewares=authelia@docker"

  server:
    image: bluewaveuptime/uptime_server:latest
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db
      - REDIS_HOST=redis
      - PAGESPEED_API_KEY=YOUR_API_KEY
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - checkmate
  redis:
    image: bluewaveuptime/uptime_redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      - checkmate
  mongodb:
    image: bluewaveuptime/uptime_database_mongo:latest
    restart: always
    volumes:
      - ./mongo/data:/data/db
    command: ["mongod", "--quiet"]
    ports:
      - "27017:27017"
    networks:
      - checkmate

networks:
  checkmate:
  traefik:
    external: true