version: "2.1"

services:

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PASSWORD=akosua123
      - SUDO_PASSWORD=akosua123 #optional
      #- SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=vscode.example.com #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/vscode/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.codeserver.rule=Host(`code.example.com`)
      - traefik.http.services.codeserver.loadbalancer.server.port=8443
      - traefik.http.routers.codeserver.tls=true
      - traefik.http.routers.codeserver.tls.certResolver=lets-encrypt
    #  # Optional part for file upload max sizes
      - traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=50000000
      - traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=50000000
      - traefik.http.middlewares.limit.buffering.memRequestBodyBytes=50000000
      - traefik.http.middlewares.limit.buffering.memResponseBodyBytes=50000000
      # Optional part for traefik middlewares
      - traefik.http.routers.codeserver.middlewares=simpleAuth@file

networks:
  web:
    external: true