

services:

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server-foo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PASSWORD=akosua123
      - SUDO_PASSWORD=akosua123 #optional
      #- SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=vscode.example.com #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/vscode/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.router-foo.rule=Path(`/foo`)

      # Definition of the router
      - traefik.http.routers.router-bar.entrypoints=traefik
      - traefik.http.routers.router-bar.middlewares=crowdsec@docker
      # Definition of the service
      - traefik.http.services.service-bar.loadbalancer.server.port=8443
      # Definitin of the middleware
      - traefik.http.middlewares.crowdsec.plugin.bouncer.enabled=true
      # crowdseclapikey is the key to authenticate to crowdsec
      - traefik.http.middlewares.crowdsec.plugin.bouncer.crowdseclapikey=FIXME-LAPI-KEY-1=
      # enable AppSec real time check
      - traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecappsecenabled=true
      # forwardedheaderstrustedips should be the IP of the proxy that is in front of traefik (if any)
      - traefik.http.middlewares.crowdsec.plugin.bouncer.forwardedheaderstrustedips=192.168.12.187

      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.nanaoware.online`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.middlewares=auth-dashboard"
      - "traefik.http.middlewares.auth-dashboard.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/" # à modifier
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"





networks:
  proxy:
    external: true