version: '3.0'

services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - "8282:80/tcp"
    environment:
      TZ: 'Europe/Brussels'
    # Volumes store your data between container upgrades
    volumes:
      - '/srv/appdata/wallos/db:/var/www/html/db'
      - '/srv/appdata/wallos/logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped