services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:80
    volumes:
      - "./data:/app/backend/data"
    # Optional healthcheck  
    healthcheck:
      test: "curl -f http://localhost/health"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    networks:
      - traefik 
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.pocketid-http.entrypoints=http"
      - "traefik.http.routers.pocketid-http.middlewares=redir-https@file"
      - "traefik.http.routers.pocketid-http.rule=Host(`pocketid.linuxpad.blog`)"
      - "traefik.http.routers.pocketid-http.service=noop@internal"
      - "traefik.http.routers.pocketid-https.entrypoints=https"
      - "traefik.http.routers.pocketid-https.tls=true"
      - "traefik.http.routers.pocketid-https.tls.certresolver=le"
      - "traefik.http.routers.pocketid-https.rule=Host(`pocketid.linuxpad.blog`)"
      - "traefik.http.routers.pocketid-https.middlewares=gzip@file,authelia@docker"
      - "traefik.http.routers.pocketid-https.service=pocketid-backend"
      - "traefik.http.services.pocketid-backend.loadbalancer.server.port=80"





networks:
  traefik:
    external: true