

services:

  app:
    image: docuseal/docuseal:latest
    container_name: docuseal
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/docuseal
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/docuseal/data:/data
    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.doc-http.entrypoints=http"
      - "traefik.http.routers.doc-http.middlewares=redir-https@file"
      - "traefik.http.routers.doc-http.rule=Host(`linuxpad.blog`)"
      - "traefik.http.routers.doc-http.service=noop@internal"
      - "traefik.http.routers.doc-https.entrypoints=https"
      - "traefik.http.routers.doc-https.tls=true"
      - "traefik.http.routers.doc-https.tls.certresolver=le"
      - "traefik.http.routers.doc-https.rule=Host(`linuxpad.blog`)"
      - "traefik.http.routers.doc-https.middlewares=gzip@file,authelia@docker"
      - "traefik.http.routers.doc-https.service=doc-backend"
      - "traefik.http.services.doc-backend.loadbalancer.server.port=3060"


  postgres:
    image: postgres:15-alpine
    container_name: docuseal-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=docuseal
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/docuseal/pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - 5432
    networks:
      - traefik

networks:
  traefik:
    external: true