services:
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: socket-proxy
    environment:
      - CONTAINERS=1
      - IMAGES=1
      - PING=1
      - VERSION=1
      - INFO=1
      - POST=1
      # Ce qui suit est utile pour la mise à jour des containers
      - ALLOW_START=1
      - ALLOW_STOP=1
      - ALLOW_RESTARTS=1
      - NETWORKS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "2375:2375"
    restart: unless-stopped

  dockpeek:
    image: dockpeek/dockpeek:latest
    container_name: dockpeek
    environment:
      # Authentification Dockpeek
      - SECRET_KEY=}k*(QMeihB!r
      - USERNAME=nana
      - PASSWORD=MotDePasseFort

      # Serveur local via socket proxy
      - DOCKER_HOST_1_URL=tcp://socket-proxy:2375
      - DOCKER_HOST_1_NAME=DNS

      # Remote serveur 2
      - DOCKER_HOST_2_URL=tcp://192.168.1.62:2375
      - DOCKER_HOST_2_NAME=StreamBox

      # Remote serveur 3
      # - DOCKER_HOST_3_URL=tcp://192.168.1.99:2375
      # - DOCKER_HOST_3_NAME=Applications
    ports:
      - "3420:8000"
    depends_on:
      - socket-proxy
    restart: unless-stopped
