version: "3"

services:
  answer:
    container_name: answer
    image: answerdev/answer
    ports:
      - '9080:80'
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/answer/data:/data
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.answer.rule=Host(`answer.nanaoware.online`) || Host(`www.answer.nanaoware.online`)
      - traefik.http.services.answer.loadbalancer.server.port=9080
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.myanswer.middlewares=mywwwredirect
      - traefik.http.routers.myanswer.middlewares=dashboard
      - traefik.http.routers.myanswer.service=api@internal
      - traefik.http.routers.myanswer.tls=true
      - traefik.http.routers.myanswer.tls.certresolver=le

networks:
  proxy:
    external: true