version: '3.8'

services:
  linkstack:
    image: linkstackorg/linkstack
    container_name: linkstack
    hostname: linkstack
    environment:
      #HTTP_SERVER_NAME: "www.example.xyz"
      #HTTPS_SERVER_NAME: "www.example.xyz"
      SERVER_ADMIN: "[email protected]"
      TZ: "Pacific/Auckland"
      PHP_MEMORY_LIMIT: "512M"
      UPLOAD_MAX_FILESIZE: "8M"
    ports:
      - "8099:80"
      - "8443:443"
    restart: unless-stopped
    volumes:
      - "linkstack:/htdocs"
volumes:
  linkstack: