version: '3'
services:
  ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    depends_on:
      - source
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.awwesome.schedule: "@daily"
      ofelia.job-run.awwesome.container: "awwesome"
  source:
    image: mkitzmann/awwesome
    container_name: awwesome
    working_dir: /usr/src/app
    environment:
      TOKEN_GITHUB: ${TOKEN_GITHUB}
    command: sh -c "npm run build && rm -r html/* && cp -r dist/* html && exit"
    volumes:
      - shared_volume:/usr/src/app/html
  web:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - shared_volume:/usr/share/nginx/html:ro
volumes:
  shared_volume: