services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: docktail-socket-proxy
    environment:
      - CONTAINERS=1
      - EVENTS=1
      - INFO=1
      - NETWORKS=1
      - POST=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker-api
    read_only: true
    tmpfs:
      - /run
    restart: unless-stopped

  docktail:
    image: ghcr.io/marvinvr/docktail:latest
    container_name: docktail-socketproxy
    depends_on:
      - socket-proxy
    environment:
      - DOCKER_HOST=tcp://socket-proxy:2375
      - TAILSCALE_OAUTH_CLIENT_ID=${TAILSCALE_OAUTH_CLIENT_ID}
      - TAILSCALE_OAUTH_CLIENT_SECRET=${TAILSCALE_OAUTH_CLIENT_SECRET}
      - DEFAULT_SERVICE_TAGS=tag:docktail-service
    volumes:
      - /var/run/tailscale:/var/run/tailscale
    networks:
      - default
      - docker-api
    restart: unless-stopped

  it-tools:
    image: ghcr.io/corentinth/it-tools:latest
    container_name: socketproxy-it-tools
    labels:
      - docktail.service.enable=true
      - docktail.service.name=tools
      - docktail.service.port=80
      - docktail.service.service-port=443
    restart: unless-stopped

  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    labels:
      - docktail.service.enable=true
      - docktail.service.name=dockhand
      - docktail.service.port=3000
      - docktail.service.service-port=443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockhand_data:/app/data

  flare:
    image: soulteary/flare
    restart: always
    command: flare
    container_name: socketproxy-flare
    environment:
      - FLARE_DISABLE_LOGIN=0
      - FLARE_USER=flare
      - FLARE_PASS=akwasi123
    labels:
      - docktail.service.enable=true
      - docktail.service.name=flare
      - docktail.service.port=5005
      - docktail.service.service-port=443
    volumes:
      - ./app:/app
  


  pwgen:
    container_name: pwgen
    image: jocxfin/pwgen:latest
    environment:
      - NO_API_CHECK=true
    command: -l 12 -n 1
    restart: unless-stopped
    labels:
      - docktail.service.enable=true
      - docktail.service.name=pwgen
      - docktail.service.port=5069
      - docktail.service.service-port=443



  picoshare:
    image: mtlynch/picoshare
    environment:
      - PS_SHARED_SECRET=dummypass 
    command: -db /data/store.db
    container_name: socketproxy-picoshare
    labels:
      - docktail.service.enable=true
      - docktail.service.name=picoshare
      - docktail.service.port=4001
      - docktail.service.service-port=443
    restart: unless-stopped
    volumes:
      - ./data:/data
      - picoshare_data:/data
 
 
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest-alpine
    environment:
      - LOG_FILE=/data/logs/access.log
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=true
      - ADMIN_TOKEN=#sPqDJ!WxJAkA
      - I_REALLY_WANT_VOLATILE_STORAGE=true
      - ROCKET_ENV=prod
      - ROCKET_WORKERS=10
      - TZ=America/Chicago
      - LOG_LEVEL=error
      - EXTENDED_LOGGING=true
    restart: unless-stopped
    labels:
      - docktail.service.enable=true
      - docktail.service.name=vaultwarden
      - docktail.service.port=4044
      - docktail.service.service-port=443
    volumes:
      - /opt/vaultwarden/data:/data
      - /opt/vaultwarden/logs:/data/logs


  vaultwarden-backup:
    container_name: vaultwarden-backup
    hostname: vaultwarden-backup
    image: bruceforce/vaultwarden-backup:latest
    init: true

    volumes:
      - /opt/vaultwarden/data:/data/
      - /opt/vaultwarden/backup:/vaultwarden-backup
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TIMESTAMP=true
      - DELETE_AFTER=30
      - UID=0
      - GID=0
      - TZ=America/Chicago
      - BACKUP_DIR=/vaultwarden-backup
      - CRON_TIME=50 3 * * *
    restart: unless-stopped
    depends_on:
      - vaultwarden
    labels:
      - docktail.service.enable=true
      - docktail.service.name=vaultwarden-backup
      - docktail.service.port=4000
      - docktail.service.service-port=443


  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: socketproxy-filebrowser
    labels:
      - docktail.service.enable=true
      - docktail.service.name=files
      - docktail.service.port=80
      - docktail.service.service-port=443
    volumes:
      - ./files:/srv
      - filebrowser-db:/database
      - filebrowser-config:/config
    restart: unless-stopped

networks:
  docker-api:
    internal: true

volumes:
  filebrowser-db:
  filebrowser-config:
  dockhand_data:
  picoshare_data:
  vaultwarden_data:

