
services:
    it-tools:
        image: 'corentinth/it-tools:latest'
        restart: unless-stopped
        container_name: it-tools
        networks:
          - traefik
        ports:
          - '3078:80'
        labels:
          - "traefik.enable=true"
          - "traefik.docker.network=traefik"
          - "traefik.http.routers.it-tools-http.entrypoints=http"
          - "traefik.http.routers.it-tools-http.middlewares=redir-https"
          - "traefik.http.routers.it-tools-http.rule=Host(`it-tools.linuxpad.blog`)"
          - "traefik.http.routers.it-tools-http.service=noop@internal"
          - "traefik.http.routers.it-tools-https.entrypoints=https"
          - "traefik.http.routers.it-tools-https.tls=true"
          - "traefik.http.routers.it-tools-https.middlewares=gzip"
          - "traefik.http.routers.it-tools-https.rule=Host(`it-tools.linuxpad.blog`)"
          - "traefik.http.services.it-tools-backend.loadbalancer.server.scheme=http"
          - "traefik.http.services.it-tools-backend.loadbalancer.server.port=80"
          - "traefik.http.routers.it-tools-https.middlewares=authelia@docker"


networks:
  traefik:
    external: true