
services:
    it-tools:
        image: 'corentinth/it-tools:latest'
        ports:
           - '8065:80'
        restart: unless-stopped
        container_name: it-tools
        networks:
          - proxy
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.it-tools.entrypoints=http"
          - "traefik.http.routers.it-tools.rule=Host(`it-tools.linuxpad.blog`)"
          - "traefik.http.middlewares.it-tools-https-redirect.redirectscheme.scheme=https"
          - "traefik.http.routers.it-tools.middlewares=it-tools-https-redirect"
          - "traefik.http.routers.it-tools-secure.entrypoints=https"
          - "traefik.http.routers.it-tools-secure.rule=Host(`it-tools.linuxpad.blog`)"
          - "traefik.http.routers.it-tools-secure.tls=true"
          - "traefik.http.routers.it-tools-secure.service=it-tools"
          - "traefik.http.services.it-tools.loadbalancer.server.port=8065"
          - "traefik.docker.network=proxy"
          - "traefik.http.routers.it-tools-secure.middlewares=authelia@docker"

networks:
  proxy:
    external: true