name: flare
services:
  flare:
    image: soulteary/flare:0.5.1
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.flare-http.entrypoints=http"
      - "traefik.http.routers.flare-http.middlewares=redir-https"
      - "traefik.http.routers.flare-http.rule=Host(`flare.linuxpad.blog`)"
      - "traefik.http.routers.flare-http.service=noop@internal"
      - "traefik.http.routers.flare-https.entrypoints=https"
      - "traefik.http.routers.flare-https.tls=true"
      - "traefik.http.routers.flare-https.middlewares=gzip"
      - "traefik.http.routers.flare-https.rule=Host(`flare.linuxpad.blog`)"
      - "traefik.http.services.flare-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.flare-backend.loadbalancer.server.port=5005"
      - "traefik.http.routers.flare-https.middlewares=authelia@docker"


networks:
  traefik:
    external: true
    