
services:
  picoshare:
    image: mtlynch/picoshare
    environment:
      - PORT=4001
      - PS_SHARED_SECRET=dummypass # Change to any password
    ports:
      - 4001:4001
    command: -db /data/store.db
    volumes:
      - ./data:/data
    networks:
      - traefik
    labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.http.routers.picoshare-http.entrypoints=http"
            - "traefik.http.routers.picoshare-http.middlewares=redir-https"
            - "traefik.http.routers.picoshare-http.rule=Host(`picoshare.linuxpad.blog`)"
            - "traefik.http.routers.picoshare-http.service=noop@internal"
            - "traefik.http.routers.picoshare-https.entrypoints=https"
            - "traefik.http.routers.picoshare-https.tls=true"
            - "traefik.http.routers.picoshare-https.middlewares=gzip"
            - "traefik.http.routers.picoshare-https.rule=Host(`picoshare.linuxpad.blog`)"
            - "traefik.http.services.picoshare-backend.loadbalancer.server.scheme=http"
            - "traefik.http.services.picoshare-backend.loadbalancer.server.port=4001"
            - "traefik.http.routers.picoshare-https.middlewares=authelia@docker"



networks:
  traefik:
    external: true