version: "3.9"
services:
  picoshare:
    image: mtlynch/picoshare
    environment:
      - PORT=4001
      - PS_SHARED_SECRET=dummypass # Change to any password
    ports:
      - 4001:4001
    command: -db /data/store.db
    volumes:
      - ./data:/data
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.picoshare.rule=Host(`pico.nanaoware.online`) || Host(`www.pico.nanaoware.online`)
      - traefik.http.services.picoshare.loadbalancer.server.port=4001
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.mypicoshare.middlewares=mywwwredirect
      - traefik.http.routers.mypicoshare.middlewares=dashboard
      - traefik.http.routers.mypicoshare.service=api@internal
      - traefik.http.routers.mypicoshare.tls=true
      - traefik.http.routers.mypicoshare.tls.certresolver=le


networks:
  proxy:
    external: true