
services:
    server:
        container_name: vaultwarden
        volumes:
            - /srv/appdata/vaultwarden:/data/'
        environment:
            - SIGNUPS_ALLOWED=true
            - ADMIN_TOKEN=#sPqDJ!WxJAkA
            - I_REALLY_WANT_VOLATILE_STORAGE=true
        ports:
            - '4044:80'
        networks:
            - proxy
        labels:
            - traefik.enable=true
            - traefik.http.routers.myvaultwarden.rule=Host(`vault.nanaoware.online`)
            - traefik.http.routers.myvaultwarden.service=api@internal
            - traefik.http.routers.myvaultwarden.middlewares=myauth
            - traefik.http.middlewares.myauth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/
    
        image: 'vaultwarden/server:latest'

networks:
    proxy:
        external: true