version: '3.8'
services:
    server:
        container_name: vaultwarden
        volumes:
            - /srv/appdata/vaultwarden:/data/'
        environment:
            - SIGNUPS_ALLOWED=true
            - ADMIN_TOKEN=#sPqDJ!WxJAkA
            - I_REALLY_WANT_VOLATILE_STORAGE=true
        ports:
            - '4044:80'
        networks:
            - web
        labels:
            - traefik.enable=true
            - traefik.docker.network=web
            - traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.nanaoware.online`)
            - traefik.http.routers.vaultwarden.entrypoints=websecure
            - traefik.http.routers.vaultwarden.tls=true
            - traefik.http.routers.vaultwarden.tls.certResolver=lets-encrypt
            - traefik.http.services.vaultwarden.loadbalancer.server.port=4044
            #  # Optional part for file upload max sizes
            - traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=50000000
            - traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=50000000
            - traefik.http.middlewares.limit.buffering.memRequestBodyBytes=50000000
            - traefik.http.middlewares.limit.buffering.memResponseBodyBytes=50000000
            #  # Optional part for traefik middlewares
            - traefik.http.routers.vaultwarden.middlewares=simpleAuth@file

        image: 'vaultwarden/server:latest'

networks:
    web:
        external: true