
services:
    server:
        container_name: vaultwarden
        volumes:
            - /srv/appdata/vaultwarden:/data/'
        environment:
            - SIGNUPS_ALLOWED=true
            - ADMIN_TOKEN=#sPqDJ!WxJAkA
            - I_REALLY_WANT_VOLATILE_STORAGE=true
        networks:
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.http.routers.vaultwarden-http.entrypoints=http"
            - "traefik.http.routers.vaultwarden-http.middlewares=redir-https"
            - "traefik.http.routers.vaultwarden-http.rule=Host(`vaultwarden.linuxpad.blog`)"
            - "traefik.http.routers.vaultwarden-http.service=noop@internal"
            - "traefik.http.routers.vaultwarden-https.entrypoints=https"
            - "traefik.http.routers.vaultwarden-https.tls=true"
            - "traefik.http.routers.vaultwarden-https.middlewares=gzip"
            - "traefik.http.routers.vaultwarden-https.rule=Host(`vaultwarden.linuxpad.blog`)"
            - "traefik.http.services.vaultwarden-backend.loadbalancer.server.scheme=http"
            - "traefik.http.services.vaultwarden-backend.loadbalancer.server.port=4044"
            - "traefik.http.routers.vaultwarden-https.middlewares=authelia@docker"


        image: 'vaultwarden/server:latest'

networks:
    traefik:
        external: true