
services:
    server:
        container_name: vaultwarden
        volumes:
            - /srv/appdata/vaultwarden:/data/'
        environment:
            - SIGNUPS_ALLOWED=true
            - ADMIN_TOKEN=#sPqDJ!WxJAkA
            - I_REALLY_WANT_VOLATILE_STORAGE=true
        ports:
            - '4044:80'
        networks:
            - proxy
        labels:
            - "traefik.enable=true"
            - traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.nanaoware.online`)
            - traefik.http.routers.vaultwarden.tls=true
            - traefik.http.routers.vaultwarden.tls.certresolver=prodresolver
            - traefik.http.routers.vaultwarden.entrypoints=websecure
            - traefik.http.services.vaultwarden.loadbalancer.server.port=80
            - traefik.http.routers.vaultwarden.service=vaultwarden
                    #Define midleware 
            - "traefik.http.routers.vaultwarden.middlewares=crowdsec-vaultwarden@docker" 
                    ## Middleware configuration
            - "traefik.http.middlewares.crowdsec-vaultwarden.plugin.crowdsec-bouncer.enabled=true"
            - "traefik.http.middlewares.crowdsec-vaultwarden.plugin.crowdsec-bouncer.crowdseclapikey=uw//V2nuhODeROUjnXQPBSYA7eOFwweLq25s1btEZHc"
            - sablier.enable=true
            - sablier.group=mygroup

        image: 'vaultwarden/server:latest'

networks:
    proxy:
        external: true