
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-conf:/etc/grafana

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    ports:
      - 8098:8080
    command: 
      - '--docker=tcp://socketproxy:2375'
      - '--housekeeping_interval=10s'
      - '--docker_only=true'
      #- '--disable_metrics=disk,network,tcp,udp,percpu,sched,process'
    labels:
      org.label-schema.group: "monitoring"
    security_opt:
      - no-new-privileges:true
    networks:
      - socket
      - proxy
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      #- /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped

volumes:
  grafana-data:
  grafana-conf:
  prometheus-data:




networks:
  proxy:
    name: proxy
    external: true #do not expose external for security risk
  socket:
    name: socket