version: '3.9'
services:
    open-resume:
        image: 'itsnoted/open-resume:latest'
        ports:
            - '3038:3000'
        restart: unless-stopped
        networks:
            - proxy
        labels:
            - traefik.enable=true
            - traefik.http.routers.open-resume.rule=Host(`resume.nanaoware.online`) || Host(`www.resume.nanaoware.online`)
            - traefik.http.services.open-resume.loadbalancer.server.port=3038
            - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
            - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
            - traefik.http.routers.myopen-resume.middlewares=mywwwredirect
            - traefik.http.routers.myopen-resume.middlewares=dashboard
            - traefik.http.routers.myopen-resume.service=api@internal
            - traefik.http.routers.myopen-resume.tls=true
            - traefik.http.routers.myopen-resume.tls.certresolver=le


networks:
  proxy:
    external: true
