version: "3"

services:
  gitea:
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    hostname: gitea
    ports:
      - 3050:3000 #webgui
      - 2222:22 #ssh
    image: gitea/gitea:latest
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/gitea/data:/data
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`gitea.nanaoware.online`) || Host(`www.gitea.nanaoware.online`)
      - traefik.http.services.gitea.loadbalancer.server.port=3050
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.mygitea.middlewares=mywwwredirect
      - traefik.http.routers.mygitea.middlewares=myauth
      - traefik.http.routers.mygitea.service=api@internal


networks:
  proxy:
    external: true