

services:
  gitea:
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    hostname: gitea
    ports:
      - 3050:3000 #webgui
      - 2222:22 #ssh
    image: gitea/gitea:latest
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/gitea/data:/data
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.mygitea.rule=Host(`gitea.nanaoware.online`)
      - traefik.http.routers.mygitea.service=api@internal
      - traefik.http.routers.mygitea.middlewares=myauth
      - traefik.http.middlewares.myauth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/


networks:
  proxy:
    external: true