## docker-compose.yml



services:
 gotify:
   image: "gotify/server"
   container_name: "mygotify"
   hostname: “gotify.localhost”
   environment:
     - “GOTIFY_SERVER_PORT=80”
     - “GOTIFY_SERVER_SSL_PORT=443”
     - “GOTIFY_DEFAULTUSER_NAME=admin”
     - “GOTIFY_DEFAULTUSER_PASS=admin”
     - “GOTIFY_DATABASE_DIALECT=sqlite3”
     - "GOTIFY_DATABASE_CONNECTION=db/gotify.db"
   volumes:
     - "./gotify_data:/app/data"
     - "/etc/localtime:/etc/localtime:ro"
   restart: unless-stopped
   ports:
     - "8447:80"
   networks:
      - proxy
   labels:
      - traefik.enable=true
      - traefik.http.routers.mygotify.rule=Host(`gotify.nanaoware.online`)
      - traefik.http.routers.mygotify.service=api@internal
      - traefik.http.services.mygotify.loadbalancer.server.port=8447
      - traefik.http.routers.mygotify.tls=true
      - traefik.http.routers.mygotify.tls.certresolver=le
      - traefik.http.routers.mygotify.middlewares=myauth
      - traefik.http.middlewares.myauth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/

networks:
  proxy:
    external: true #do not expose external for security risk

