
services:
  gotify:
    image: gotify/server
    container_name: gotify
    volumes:
      - /home/nana/gotify:/app/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    environment:
      - TZ=Europe/London
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.gotify-http.entrypoints=http"
      - "traefik.http.routers.gotify-http.middlewares=redir-https"
      - "traefik.http.routers.gotify-http.rule=Host(`gotify.linuxpad.blog`)"
      - "traefik.http.routers.gotify-http.service=noop@internal"
      - "traefik.http.routers.gotify-https.entrypoints=https"
      - "traefik.http.routers.gotify-https.tls=true"
      - "traefik.http.routers.gotify-https.middlewares=gzip"
      - "traefik.http.routers.gotify-https.rule=Host(`gotify.linuxpad.blog`)"
      - "traefik.http.services.gotify-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.gotify-backend.loadbalancer.server.port=80"
      - "traefik.http.routers.gotify-https.middlewares=authelia@docker"
networks:
  traefik:
    external: true## docker-compose.yml














