## docker-compose.yml



services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    hostname: gotify
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - data:/app/data
    environment:
      GOTIFY_DEFAULTUSER_PASS: "password"
      GOTIFY_DEFAULTUSER_NAME: "admin"
      GOTIFY_REGISTRATION: "false"
    labels:
      - traefik.docker.network=proxy
      - traefik.enable=true
      - traefik.http.routers.gotify.rule=Host(`gotify.nanaoware.online`) || Host(`www.gotify.nanaoware.online`)
      - traefik.http.services.homepage.loadbalancer.server.port=8447
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.mygotify.middlewares=myauth
      - traefik.http.routers.mygotify.service=api@internal
      - traefik.http.routers.mygotify.tls=true
      - traefik.http.routers.mygotify.tls.certresolver=myresolver
    
  igotify-notification:
    image: ghcr.io/androidseb25/igotify-notification-assist:latest
    container_name: igotify
    hostname: igotify
    restart: unless-stopped
    pull_policy: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - api-data:/app/data
    environment:
      GOTIFY_URLS: "192.168.8.188:8447"
      GOTIFY_CLIENT_TOKENS: ""
      SECNTFY_TOKENS: ""
    labels:
      - traefik.docker.network=proxy
      - traefik.enable=true
      - traefik.http.routers.igotify.rule=Host(`igotify.nanaoware.online`) || Host(`www.igotify.nanaoware.online`)
      - traefik.http.services.igotify.loadbalancer.server.port=8447
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.myigotify.middlewares=myauth
      - traefik.http.routers.myigotify.service=api@internal
      - traefik.http.routers.myigotify.tls=true
      - traefik.http.routers.myigotify.tls.certresolver=myresolver
    networks:
      - proxy


networks:
  proxy:
    external: true

volumes:
  data:
  api-data:


    

   
 