
networks:
  net:
    driver: bridge
services:
  traefik:
    container_name: 'traefik'
    image: 'traefik:v3.1'
    restart: 'unless-stopped'
    command:
      - '--api=true'
      - '--api.dashboard=true'
      - '--api.insecure=false'
      - '--pilot.dashboard=false'
      - '--global.sendAnonymousUsage=false'
      - '--global.checkNewVersion=false'
      - '--log=true'
      - '--log.level=DEBUG'
      - '--log.filepath=/config/traefik.log'
      - '--metrics.prometheus=true'
      - '--metrics.prometheus.buckets=0.1,0.3,1.2,5.0'
      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--entryPoints.http=true'
      - '--entryPoints.http.address=:8080/tcp'
      - '--entryPoints.http.http.redirections.entryPoint.to=https'
      - '--entryPoints.http.http.redirections.entryPoint.scheme=https'
      ## Please see the Forwarded Header Trust section of the Authelia Traefik Integration documentation.
      # - '--entryPoints.http.forwardedHeaders.trustedIPs=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,fc00::/7'
      # - '--entryPoints.http.proxyProtocol.trustedIPs=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,fc00::/7'
      - '--entryPoints.http.forwardedHeaders.insecure=false'
      - '--entryPoints.http.proxyProtocol.insecure=false'
      - '--entryPoints.https=true'
      - '--entryPoints.https.address=:8443/tcp'
      - '--entrypoints.https.http.tls.certresolver=myresolver'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesResolvers.myresolver.acme.email=owarenana06@gmail.com'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'


      ## Please see the Forwarded Header Trust section of the Authelia Traefik Integration documentation.
      - '--entryPoints.https.forwardedHeaders.trustedIPs=10.0.0.0/8,172.16.0.0/12,192.168.8.1/24,fc00::/7'
      - '--entryPoints.https.proxyProtocol.trustedIPs=10.0.0.0/8,172.16.0.0/12,192.168.8.1/24,fc00::/7'
      - '--entryPoints.https.forwardedHeaders.insecure=false'
      - '--entryPoints.https.proxyProtocol.insecure=false'
    networks:
      net: {}
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${PWD}/data/traefik:/config'
      - '/letsencrypt:/letsencrypt'

    labels:
      - traefik.enable:true
      - traefik.http.routers.api.rule:Host(`traefik.nanaoware.online`)
      - traefik.http.routers.api.entryPoints:https
      - traefik.http.routers.api.tls:true
      - traefik.http.routers.api.service:api@internal
      - traefik.http.middlewares.auth.basicauth.users="test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/"
      - traefik.http.routers.api.middlewares:authelia@docker
  
  authelia:
    container_name: 'authelia'
    image: 'authelia/authelia'
    restart: 'unless-stopped'
    networks:
      net: {}
    volumes:
      - '${PWD}/data/authelia/config:/config'
    environment:
      TZ: "Australia/Melbourne"
    labels:
      - 'traefik.enable:true'
      - 'traefik.http.routers.authelia.rule:Host(`auth.nanaoware.online`)'
      - 'traefik.http.routers.authelia.entryPoints:https'
      - 'traefik.http.routers.authelia.tls:true'
      - 'traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https://auth.nanaoware.online'
      - 'traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader:true'
      - 'traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
      - 'traefik.http.middlewares.authelia-basic.forwardAuth.address=http://authelia:9091/api/verify?auth=basic'
      - 'traefik.http.middlewares.authelia-basic.forwardAuth.trustForwardHeader:true'
      - 'traefik.http.middlewares.authelia-basic.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
      - 'traefik.http.services.authelia.loadbalancer.server.port=9091'


  nextcloud:
    container_name: 'nextcloud'
    image: 'linuxserver/nextcloud'
    restart: 'unless-stopped'
    networks:
      net: {}
    volumes:
      - '${PWD}/data/nextcloud/config:/config'
      - '${PWD}/data/nextcloud/data:/data'
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: 'Australia/Melbourne'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.nextcloud.rule: 'Host(`nextcloud.nanaoware.online`)'
      traefik.http.routers.nextcloud.entryPoints: 'https'
      traefik.http.routers.nextcloud.tls: 'true'
      traefik.http.routers.nextcloud.middlewares: 'authelia@docker'
  heimdall:
    container_name: 'heimdall'
    image: 'linuxserver/heimdall'
    restart: 'unless-stopped'
    networks:
      net: {}
    volumes:
      - '${PWD}/data/heimdall/config:/config'
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: 'Australia/Melbourne'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.heimdall.rule: 'Host(`heimdall.nanaoware.online`)'
      traefik.http.routers.heimdall.entryPoints: 'https'
      traefik.http.routers.heimdall.tls: 'true'
      traefik.http.routers.heimdall.middlewares: 'authelia-basic@docker'
...




volumes:
  letsencrypt:
    name: letsencrypt

