services:
  traefik:
    image: "traefik:latest"
    ports:
      - "80:80"
      - "8080:8080"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  apache:
    image: "httpd:latest"
    labels:
     - "traefik.http.routers.apache.rule=Host(`webserver.localhost`)"
     - "traefik.http.routers.apache.service=apache-serv"
     - "traefik.http.services.apache-serv.loadbalancer.server.port=80"
