[http.middlewares.simpleAuth.basicAuth]
  users = [
    "nana:$apr1$10jy6hpm$gx2gI5Epl7/PaPSUnYBPq/"
  ]

[http.routers.api]
  rule = "Host(`monitor.your_domain`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"