title: "linuxpad"
home: "/"
logo: "https://belginux.com/content/images/2024/01/bbbbb-8.png"
github:
  - owner: "rajnandan1"
    repo: "kener"
    incidentSince: 48
metaTags:
  description: "Kener: Open-source modern looking Node.js status page tool, designed to make service monitoring and incident handling a breeze. It offers a sleek and user-friendly interface that simplifies tra>
  keywords: "Node.js status page, Incident management tool, Service monitoring, Service outage tracking, Real-time status updates, GitHub integration for incidents, Open-source status page, Node.js monitoring >
  og:description: "Kener: Open-source Node.js status page tool, designed to make service monitoring and incident handling a breeze. It offers a sleek and user-friendly interface that simplifies tracking servic>
  og:image: "https://kener.ing/ss.png"
  og:title: "Kener - Open-Source and Modern looking Node.js Status Page for Effortless Incident Management"
  og:type: "website"
  og:site_name: "Kener"
  twitter:card: "summary_large_image"
  twitter:site: "@_rajnandan_"
  twitter:creator: "@_rajnandan_"
  twitter:image: "https://kener.ing/ss.png"
  twitter:title: "Kener: Open-Source and Modern looking Node.js Status Page for Effortless Incident Management"
  twitter:description: "Kener: Open-source Node.js status page tool, designed to make service monitoring and incident handling a breeze. It offers a sleek and user-friendly interface that simplifies tracking s>
nav:
  - name: "Documentation"
    url: "/docs"
  - name: "Github"
    url: "https://github.com/rajnandan1/kener"
hero:
  title: Page des statuts belginux
  subtitle: Tant que tout n'est pas rouge, tout va bien!
footerHTML: |
  Made using 
  <a href="https://github.com/rajnandan1/kener" target="_blank" rel="noreferrer" class="font-medium underline underline-offset-4">
    Kener
  </a>
  an open source status page system built with Svelte and TailwindCSS.