################################################################################
# HOMELAB
################################################################################

include:
    #############################################################################
    # TRAEFIK (CORE)
    #############################################################################

    - apps/traefik.yaml # Traefik (Reverse Proxy) + Socket-Proxy + Authelia
    - apps/zitadel.yaml # Zitadel (Security)
    - apps/flare.yaml # Flare (Dashboard)
    - apps/bunker-web.yaml # Bunker Web (Bouncer)
    - apps/fial2ban.yaml # Fail2Ban (Security)

    #############################################################################
    # MEDIA
    #############################################################################

    - apps/immich.yaml # Immich (Photos Backup)
    - apps/owncloud.yaml # Owncloud (Data Server)
    - apps/nextcloud.yaml # Nextcloud (Home Server)
    - apps/hoarder.yaml # Hoarder (Bookmarks Manager)
    - apps/paperless.yaml # Paperless (File Storage)
    - apps/link.yaml # Little-link (Link Page)
    - apps/it-tools.yaml # Tools (It Tools)
    - apps/cronicle.yaml # Cronicle (Cron Job)
    - apps/gitea.yaml # Gitea (Git Server)
    - apps/photoprism.yaml # Photoprism (Photo Management)

    #############################################################################
    # UTILITIES
    #############################################################################

    - apps/watchtower.yaml #  Watchtower (Container Updating)
    - apps/diun.yaml # Diun (Docker Image Update Notifier)
    - apps/speed-test.yaml # Speedtest (Internet Speed Test)
    - apps/pihole.yaml # Pi-hole (DNS Ad-Blocking)
    - apps/portainer.yaml # Portainer (Container Management)
    - apps/uptime-kuma.yaml # Uptime Kuma (Monitoring)
    - apps/restic.yaml # Restic (Backup)
    - apps/vaultwarden.yaml # Vaultwarden (Password Manager)
    - apps/umami.yaml # Umami (Analytics)
    - apps/pwgen.yaml # Pwgen (Password Generator)
    - apps/ghost.yaml # Ghost (Blog)
    - apps/wordpress.yaml # Wordpress (Blog)
    - apps/rxresume.yaml # RxResume (Resume)
    - apps/gotify.yaml # Gotify (Notification)
    - apps/glance.yaml # Glances (System Monitor)
    - apps/tor.yaml # Tor (Anonymity)
    - apps/dozzle.yaml # Dozzle (Log Viewer)
    - apps/beszel.yaml # Beszel (Log Viewer)

    #############################################################################
    # MISCELLANEOUS
    #
    # * Note the existing services that are disabled by default.
    #############################################################################

    # - apps/chat-gpt-next-web.yaml # ChatGPT Next Web
    - apps/pico-share.yaml # File Sharing
    - apps/ollama.yaml # Ollama (AI Suite)
    - apps/deepseek.yaml # Deepseek Analytics
    - apps/homeassistant/docker-compose.yaml # Home Assistant (Smart Home)
    - apps/healthchecks.yaml # Healthchecks (Monitoring)

################################################################################
# NETWORK CONFIGURATION
################################################################################

networks:
  traefik:
    external: true
  dockersocket:
    name: dockersocket
