version: "3.9"
services:
  resume-db:
    image: postgres:16
    container_name: RXRESUME-DB
    hostname: resume-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "reresume", "-U", "reresumeuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /volume1/docker/rxv3/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: reresume
      POSTGRES_USER: reresumeuser
      POSTGRES_PASSWORD: reresumepw
    restart: on-failure:5

  resume-server:
    image: amruthpillai/reactive-resume:server-3.8.4
    container_name: RXRESUME-SERVER
    hostname: resume-server
    security_opt:
      - no-new-privileges:true
    ports:
      - 8661:3100
    volumes:
      - /volume1/docker/rxv3/exports:/app/server/dist/assets/exports:rw
      - /volume1/docker/rxv3/uploads:/app/server/dist/assets/uploads:rw
    environment:
      - PUBLIC_URL=https://rxresume.yourname.synology.me
      - PUBLIC_SERVER_URL=https://rxresumeserver.yourname.synology.me
      - POSTGRES_DB=reresume
      - POSTGRES_USER=reresumeuser
      - POSTGRES_PASSWORD=reresumepw
      - SECRET_KEY=MariushostingMariushostingMari13
      - POSTGRES_HOST=resume-db
      - POSTGRES_PORT=5432
      - JWT_SECRET=MariushostingMariushostingMari13
      - JWT_EXPIRY_TIME=604800
      - MAIL_FROM_NAME=Reactive Resume
      - MAIL_FROM_EMAIL=Your-own-gmail-address
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=Your-own-gmail-address
      - MAIL_PASSWORD=Your-own-app-password
    restart: on-failure:5
    depends_on:
      resume-db:
        condition: service_started

  resume-client:
    image: amruthpillai/reactive-resume:client-3.8.4
    container_name: RXRESUME-CLIENT
    hostname: resume-client
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: curl -fSs 127.0.0.1:3000 || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - 8662:3000
    environment:
      - PUBLIC_URL=https://rxresume.yourname.synology.me
      - PUBLIC_SERVER_URL=https://rxresumeserver.yourname.synology.me
    restart: on-failure:5
    depends_on:
      resume-server:
        condition: service_started
