
services:
  nexterm:
    ports:
      - "6989:6989"
    restart: always
    volumes:
      - ./nexterm:/app/data
    image: germannewsmaker/nexterm:1.0.1-OPEN-PREVIEW

    networks:
      - proxy
      - socket
    labels:
      - traefik.enable=true
      - traefik.http.routers.mynexterm.rule=Host(`nexterm.nanaoware.online`)
      - traefik.http.routers.mynexterm.service=api@internal
      - traefik.http.routers.mynexterm.middlewares=myauth
      - traefik.http.middlewares.myauth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/
      - sablier.enable=true
      - sablier.group=mygroup



networks:
  proxy:
    name: proxy
    external: true #do not expose external for security risk
  socket:
    name: socket
