
services:
  nexterm:
    ports:
      - "6989:6989"
    restart: always
    volumes:
      - ./nexterm:/app/data
    image: germannewsmaker/nexterm:1.0.1-OPEN-PREVIEW

    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nexterm.entrypoints=http"
      - "traefik.http.routers.nexterm.rule=Host(`nexterm.linuxpad.blog`)"
      - "traefik.http.middlewares.nexterm-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nexterm.middlewares=nexterm-https-redirect"
      - "traefik.http.routers.nexterm-secure.entrypoints=https"
      - "traefik.http.routers.nexterm-secure.rule=Host(`uptime-kuma.linuxpad.blog`)"
      - "traefik.http.routers.nexterm-secure.tls=true"
      - "traefik.http.routers.nexterm-secure.service=nexterm"
      - "traefik.http.services.nexterm.loadbalancer.server.port=6989"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.nexterm-secure.middlewares=authelia@docker"



networks:
  proxy:
    name: proxy
    external: true #do not expose external for security risk
