version: "3.3"

services:
  backup:
    image: mazzolino/restic
    container_name: restic
    hostname: nana
    environment:
      RUN_ON_STARTUP: "true" #change as you wish
      BACKUP_CRON: "0 */12 * * *" #this is twice daily, i.e., every 12 hours
      RESTIC_REPOSITORY: /restic
      RESTIC_PASSWORD: Afiaanimah*123
      RESTIC_BACKUP_SOURCES: /mnt/docker-volumes  /home/nana
      RESTIC_COMPRESSION: auto 
      RESTIC_BACKUP_ARGS: >-
        --tag docker-volumes
        --exclude some-folder/cache
        --exclude another-folder/with\ space
        --exclude *.tmp
        --verbose
      RESTIC_FORGET_ARGS: >- #change as required
        --keep-last 10
        --keep-daily 7
        --keep-weekly 5
        --keep-monthly 12
      TZ: Europe/London
    volumes:
      - /home/nana/nas/backup:/restic #change the left hand side to where you want to store the backups. As you can see I'm storing it on my NAS that is mounted to the host /home/truenas
      - /home/nana/nas/tmp-for-restore:/tmp-for-restore#USE THIS FOLDER FOR RESTORE - CAN VIEW EACH CONTAINER
      - /var/lib/docker/volumes:/mnt/docker-volumes:ro
      - /home/nana:/home/nana:ro
    security_opt:
      - no-new-privileges:true

  prune:
    image: mazzolino/restic
    container_name: restic-prune
    hostname: nana
    environment:
      RUN_ON_STARTUP: "true"
      PRUNE_CRON: "0 0 4 * * *"
      RESTIC_REPOSITORY: /restic
      RESTIC_PASSWORD: Afiaanimah*123
      TZ: Europe/London
    security_opt:
      - no-new-privileges:true

  check:
    image: mazzolino/restic
    container_name: restic-check
    hostname: nana
    environment:
      RUN_ON_STARTUP: "false"
      CHECK_CRON: "0 15 5 * * *"
      RESTIC_CHECK_ARGS: >-
        --read-data-subset=10%
      RESTIC_REPOSITORY: /restic
      RESTIC_PASSWORD: Afiaanimah*123
      TZ: Europe/London
    security_opt:
      - no-new-privileges:true
