name: flare
services:
  flare:
    image: soulteary/flare:0.5.1
    networks:
      - traefik
    volumes:
      - ./app:/app
    command: flare
    environment:
      # 开启登陆
      - FLARE_DISABLE_LOGIN=0
      # 设置登陆账号
      - FLARE_USER=flare
      # 指定你自己的账号密码，如未设置 `FLARE_USER`，则会默认生成密码并展示在应用启动日志中
      - FLARE_PASS=akwasi123
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.wazuh-http.entrypoints=http"
      - "traefik.http.routers.wazuh-http.middlewares=redir-https@file"
      - "traefik.http.routers.wazuh-http.rule=Host(`wazuh.linuxpad.blog`)"
      - "traefik.http.routers.wazuh-http.service=noop@internal"
      - "traefik.http.routers.wazuh-https.entrypoints=https"
      - "traefik.http.routers.wazuh-https.tls=true"
      - "traefik.http.routers.wazuh-https.tls.certresolver=le"
      - "traefik.http.routers.wazuh-https.rule=Host(`wazuh.linuxpad.blog`)"
      - "traefik.http.routers.wazuh-https.middlewares=gzip@file,authelia@docker"
      - "traefik.http.routers.wazuh-https.service=wazuh-backend"
      - "traefik.http.services.wazuh-backend.loadbalancer.server.port=5005"


networks:
  traefik:
    external: true
