services:
  # Dockge - Docker Compose Manager
  dockge:
    image: louislam/dockge
    container_name: dockge
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "5001:5001"
    networks:
      - proxy
      - socket
    volumes:
      - /dockge:/app/data
      - /test:/opt/stacks
    environment:
      #- DOCKGE_STACKS_DIR=/opt/stacks
      - DOCKER_HOST=tcp://socketproxy:2375
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.dockge-rtr.entrypoints=websecure"
      - "traefik.http.routers.dockge-rtr.rule=Host(`dockge.$DOMAINNAME_HS`)"
      # Middlewares
      - "traefik.http.routers.dockge-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.dockge-rtr.service=dockge-svc"
      - "traefik.http.services.dockge-svc.loadbalancer.server.port=5001"

networks:
  proxy:
    name: proxy
    external: true #do not expose external for security risk
  socket:
    name: socket
