services:
  # IT-Tools - Status Page & Monitoring Server
  it-tools:
    image: corentinth/it-tools
    container_name: it-tools
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.codeserver.rule=Host(`tools.nanaoware.online`) || Host(`www.tools.nanaoware.online`)
      - traefik.http.services.codeserver.loadbalancer.server.port=80
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.mycodeserver.middlewares=mywwwredirect
      - traefik.http.routers.mycodeserver.middlewares=myauth
      - traefik.http.routers.mycodeserver.service=api@internal

networks:
  proxy:
    name: proxy
    external: true #do not expose external for security risk
  socket:
    name: socket