services:
  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-web
    container_name: scrutiny
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - proxy
    ports:
      - 8090:8080
    volumes:
      - $DOCKERDIR/appdata/scrutiny:/opt/scrutiny/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.codeserver.rule=Host(`code.nanaoware.online`) || Host(`www.code.nanaoware.online`)
      - traefik.http.services.codeserver.loadbalancer.server.port=8443
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.mycodeserver.middlewares=mywwwredirect
      - traefik.http.routers.mycodeserver.middlewares=myauth
      - traefik.http.routers.mycodeserver.service=api@internal
