services:
  # Autoindex - Simple Directory Index (for Sitespeed.io Results)
  sitespeed:
    container_name: sitespeed
    image: dceoy/nginx-autoindex:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - $EXTDRIVE/ssd/sitespeed:/var/lib/nginx/html:ro # Location you want to index
    labels:
      - traefik.enable=true
      - traefik.http.routers.codeserver.rule=Host(`code.nanaoware.online`) || Host(`www.code.nanaoware.online`)
      - traefik.http.services.codeserver.loadbalancer.server.port=8443
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.mycodeserver.middlewares=mywwwredirect
      - traefik.http.routers.mycodeserver.middlewares=myauth
      - traefik.http.routers.mycodeserver.service=api@internal
