version: '3.9'

services:

  wordpress:
    depends_on:
      - db
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wp:/var/www/html/

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  db_backup:
    container_name: db_backup
    image: tiredofit/db-backup
    depends_on:
      - mysql
    volumes:
      - ../backups/danielpetrica_com/ghost_db/:/backup
      #- ./post-script.sh:/assets/custom-scripts/post-script.sh
    environment:
      # - DEBUG_MODE=TRUE
      - DB_TYPE=mysql
      - DB_HOST=ghost_mysql
      - DB_NAME=${DATABASE__CONNECTION__DATABASE}
      - DB_USER=root
      - DB_PASS=${DATABASE__CONNECTION__PASSWORD}
      - DB_DUMP_FREQ=720          # backup 12 hours 12 * 60
      # - DB_DUMP_BEGIN=0000      # backup starts immediately
      - DB_CLEANUP_TIME=72000     # clean backups that are older than 72000 minutes
      - CHECKSUM=SHA1
      - COMPRESSION=GZ
      - SPLIT_DB=true
      - CONTAINER_ENABLE_MONITORING=FALSE
    restart: always

  wpcli:
    image: wordpress:cli
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wp:/var/www/html/
    depends_on:
      - db
      - wordpress
    
  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  db:

networks:
  default:
    external: true
    name: proxy
