

services:

  cronicle:
    image: soulteary/cronicle:0.9.63
    restart: always
    hostname: cronicle
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/data:/opt/cronicle/data
      - ./data/logs:/opt/cronicle/logs
      - ./data/plugins:/opt/cronicle/plugins
    extra_hosts:
      - "cronicle.lab.io:0.0.0.0"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - traefik
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:3012/api/app/ping || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 3
    logging:
        driver: "json-file"
        options:
            max-size: "10m"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.cronicle-http.entrypoints=http"
      - "traefik.http.routers.cronicle-http.middlewares=redir-https"
      - "traefik.http.routers.cronicle-http.rule=Host(`cronicle.linuxpad.blog`)"
      - "traefik.http.routers.cronicle-http.service=noop@internal"
      - "traefik.http.routers.cronicle-https.entrypoints=https"
      - "traefik.http.routers.cronicle-https.tls=true"
      - "traefik.http.routers.cronicle-https.middlewares=gzip"
      - "traefik.http.routers.cronicle-https.rule=Host(`cronicle.linuxpad.blog`)"
      - "traefik.http.services.cronicle-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.cronicle-backend.loadbalancer.server.port=3012"
      - "traefik.http.routers.cronicle-https.middlewares=authelia@docker"


networks:
  traefik:
    name: traefik
    external: true #do not expose external for security risk
  