

services:
  watchtower:
    container_name: watchtower
    hostname: watchtower
    environment:
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${SMTP_PORT:-587}
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${SMTP_USER:-smtpuser}
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${SMTP_PASS:-smtppass}
      #- WATCHTOWER_NOTIFICATION_EMAIL_FROM=${SMTP_MAIL_FROM:-watchtower@example.com}
      #- WATCHTOWER_NOTIFICATION_EMAIL_TO=${SMTP_MAIL_TO:-watchtower@example.com}
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${SMTP_SERVER:-smtp.google.com}
      - WATCHTOWER_HTTP_API_TOKEN=${API_TOKEN:-SecureApiToken}
      #- WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_DEBUG=true
      - DOCKER_HOST=tcp://dockersocket:2375

      - WATCH_TOWER_HTTP_API_METRICS=true
      #- WATCH_TOWER_HTTP_API_TOKEN="mytoken"
      #new- TZ=$TZ
      - WATCHTOWER_MONITOR_ONLY=false
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=telegram://$TELEGRAM_AUTH_TOKEN@telegram?channels=$TELEGRAM_CHAT_ID&parseMode=HTML
      - WATCHTOWER_NOTIFICATION_TEMPLATE=📊🔔⚡️ <b>Server:</b> <code>Update</code>{{println}}{{range .}}{{.Message}}{{println}}{{end}}
      - WATCHTOWER_NOTIFICATION_SKIP_TITLE=true
      - WATCHTOWER_SCHEDULE=0 0 6 * * * # requires a go cron syntax of 6 space-separated fields; see https://containrrr.dev/watchtower/arguments/#scheduling
      #- WATCHTOWER_CLEANUP=true # remove unused images afterwards
    image: containrrr/watchtower:latest
    networks:
      - proxy
      - dockersocket
    labels:
      - traefik.enable=true
      - traefik.enable=true
      - traefik.http.routers.mywatchtower.rule=Host(`watchtower.nanaoware.online`)
      - traefik.http.routers.mywatchtower.service=api@internal
      - traefik.http.routers.mywatchtower.middlewares=myauth
      - traefik.http.middlewares.mywatchtower.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/


    restart: always
    #network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
     # - /var/run/docker.sock:/var/run/docker.sock:ro # Disable for socket proxy
    ports:
      - 8080:8080
    working_dir: /

networks:
  proxy:
    name: proxy
  dockersocket:
    name: dockersocket
