version: "3.9"

services:
  adguard:
    container_name: adguard
    hostname: adguard
    image: adguard/adguardhome:latest
    ports:
      - 3000:3000/tcp # only required during initial setup
      - 8080:80/tcp # web interface after setup
      - 53:53/tcp # dns
      - 53:53/udp # dns
      # - 67:67/udp # dhcp
      # - 68:68/tcp # dhcp
      # - 68:68/udp # dhcp
      # - 784:784/udp # dns-over-quic
      # - 853:853/tcp # dns over tls
      # - 853:853/udp # dns over tls
      # - 5443:5443/tcp # dnscrypt
      # - 5443:5443/udp # dnscrypt
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/adguard-home/work:/opt/adguardhome/work
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/adguard-home/conf:/opt/adguardhome/conf
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.rule=Host(`dns.nanaoware.online`) || Host(`www.dns.nanaoware.online`)
      - traefik.http.services.adguard.loadbalancer.server.port=3000
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.myadguard.middlewares=mywwwredirect
      - traefik.http.routers.myadguard.middlewares=myauth
      - traefik.http.routers.myadguard.service=api@internal


networks:
  proxy:
    external: true