version: "3.8"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /mnt/media:/config
      - /mnt/media/Tv-Shows:/data/Tv-Shows
      - /mnt/media/Movies:/data/Movies
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.nanaoware.online`) || Host(`www.jellyfin.nanaoware.online`)
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.myjellyfin.middlewares=mywwwredirect
      - traefik.http.routers.myjellyfin.middlewares=myauth
      - traefik.http.routers.myjellyfin.service=api@internal

    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
networks:
  proxy:
    external: true
