services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    environment:
      - WUD_WATCHER_LOCAL_CRON=0 6 * * *
      - WUD_AUTH_BASIC_MY_USER=test
      - WUD_AUTH_BASIC_MY_HASH=$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/
     # - WUD_TRIGGER_SMTP_GMAIL_HOST=smtp.gmail.com
     # - WUD_TRIGGER_SMTP_GMAIL_PORT=465
     # - WUD_TRIGGER_SMTP_GMAIL_USER=owarenana06@gmail.com
     # - WUD_TRIGGER_SMTP_GMAIL_PASS=
     # - WUD_TRIGGER_SMTP_GMAIL_FROM=owarenana06@gmail.com
     # - WUD_TRIGGER_SMTP_GMAIL_TO=owarenana06@gmail.com
     # - WUD_TRIGGER_SMTP_GMAIL_TLS_ENABLED=true 
      - WUD_UI_BASE_URL=https://wud.linuxpad.blog
      - WUD_TRIGGER_DOCKER_LOCAL_PRUNE=true
      - WUD_TRIGGER_TELEGRAM_1_BOTTOKEN=8235308938:AAHYIx_7cq2Q_vXYeZov_QsFbKvC7_kNqF0
      - WUD_TRIGGER_TELEGRAM_1_CHATID=7368408781


    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.wud-http.entrypoints=http"
      - "traefik.http.routers.wud-http.middlewares=redir-https"
      - "traefik.http.routers.wud-http.rule=Host(`wud.linuxpad.blog`)"
      - "traefik.http.routers.wud-http.service=noop@internal"
      - "traefik.http.routers.wud-https.entrypoints=https"
      - "traefik.http.routers.wud-https.tls=true"
      - "traefik.http.routers.wud-https.middlewares=gzip"
      - "traefik.http.routers.wud-https.rule=Host(`wud.linuxpad.blog`)"
      - "traefik.http.services.wud-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.wud-backend.loadbalancer.server.port=3000"
      - "traefik.http.routers.wud-https.middlewares=authelia@docker"
    restart: always


    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  traefik:
    external: true
