
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    ports:
      - 9999:8080
    environment:
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_HOSTNAME=Nana's Docker Lab
      - DOZZLE_LEVEL=info
      - DOZZLE_TAILSIZE=300
      - DOZZLE_FILTER="status=running"
      # DOZZLE_FILTER: "label=log_me" # limits logs displayed to containers with this label

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dozzle-data:/data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.dozzle.rule=Host(`dozzle.nanaoware.online`)
      - traefik.http.routers.dozzle.tls=true
      - traefik.http.routers.dozzle.tls.certresolver=prodresolver
      - traefik.http.routers.dozzle.entrypoints=websecure
      - traefik.http.services.dozzle.loadbalancer.server.port=80
      - traefik.http.routers.dozzle.service=dozzle
      #Define midleware 
      - "traefik.http.routers.dozzle.middlewares=crowdsec-dozzle@docker" 
      ## Middleware configuration
      - "traefik.http.middlewares.crowdsec-dozzle.plugin.crowdsec-bouncer.enabled=true"
      - "traefik.http.middlewares.crowdsec-dozzle.plugin.crowdsec-bouncer.crowdseclapikey=uw//V2nuhODeROUjnXQPBSYA7eOFwweLq25s1btEZHc"

networks:
  proxy:
    external: true