
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    ports:
      - 9999:8080
    environment:
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_HOSTNAME=Nana's Docker Lab
     # - DOCKER_HOST=tcp://socket-proxy:2375
      - DOZZLE_LEVEL=info
      - DOZZLE_TAILSIZE=300
      - DOZZLE_FILTER="status=running"
      # DOZZLE_FILTER: "label=log_me" # limits logs displayed to containers with this label

    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock
      - ./dozzle-data:/data
    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.entrypoints=http"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.linuxpad.blog`)"
      - "traefik.http.middlewares.dozzle-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dozzle.middlewares=dozzle-https-redirect"
      - "traefik.http.routers.dozzle-secure.entrypoints=https"
      - "traefik.http.routers.dozzle-secure.rule=Host(`dozzle.linuxpad.blog`)"
      - "traefik.http.routers.dozzle-secure.tls=true"
      - "traefik.http.routers.dozzle-secure.service=dozzle"
      - "traefik.http.services.dozzle.loadbalancer.server.port=9999"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.dozzle-secure.middlewares=authelia@docker"

networks:
  proxy:
    name: proxy
    external: true #do not expose external for security risk
 