
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_HOSTNAME=Nana's Docker Lab
      - DOZZLE_LEVEL=info
      - DOZZLE_TAILSIZE=300
      - DOZZLE_FILTER="status=running"
      # DOZZLE_FILTER: "label=log_me" # limits logs displayed to containers with this label

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dozzle-data:/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.beszel-http.entrypoints=http"
      - "traefik.http.routers.beszel-http.middlewares=redir-https"
      - "traefik.http.routers.beszel-http.rule=Host(`beszel.linuxpad.blog`)"
      - "traefik.http.routers.beszel-http.service=noop@internal"
      - "traefik.http.routers.beszel-https.entrypoints=https"
      - "traefik.http.routers.beszel-https.tls=true"
      - "traefik.http.routers.beszel-https.middlewares=gzip"
      - "traefik.http.routers.beszel-https.rule=Host(`beszel.linuxpad.blog`)"
      - "traefik.http.services.beszel-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.beszel-backend.loadbalancer.server.port=8099"
      - "traefik.http.routers.beszel-https.middlewares=authelia@docker"


networks:
  traefik:
    name: traefik
    external: true #do not expose external for security risk
 