version: "3.3"
services:
  dozzle:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    image: amir20/dozzle
    command: --username nana --password akosua123
networks: {}
