version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    ports:
      - 9999:8080
    environment:
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_HOSTNAME=Lab2 Server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dozzle-data:/data