
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    ports:
      - 9999:8080
    environment:
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_HOSTNAME=Nana's Docker Lab
      - DOCKER_HOST=tcp://socketproxy:2375
      - DOZZLE_LEVEL=info
      - DOZZLE_TAILSIZE=300
      - DOZZLE_FILTER="status=running"
      # DOZZLE_FILTER: "label=log_me" # limits logs displayed to containers with this label

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dozzle-data:/data
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.rule=Host(`dozzle.nanaoware.online`) || Host(`www.dozzle.nanaoware.online`)
      - traefik.http.services.dozzle.loadbalancer.server.port=9999
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.mydozzle.middlewares=mywwwredirect
      - traefik.http.routers.mydozzle.middlewares=myauth
      - traefik.http.routers.mydozzle.service=api@internal
networks:
  proxy:
    external: true
