version: "3.3"
services:
  dozzle:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    environment:
      - DOZZLE_AUTH_PROVIDER=simple
    image: amir20/dozzle:latest
    command: --username nana --password akosua123
networks: {}
