version: '3.7'

services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8088
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8088:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak_network
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak.rule=Host(`key.nanaoware.online`) || Host(`www.key.nanaoware.online`)
      - traefik.http.services.keycloak.loadbalancer.server.port=2368
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.mykeycloak.middlewares=mywwwredirect
      - traefik.http.routers.mykeycloak.middlewares=myauth
      - traefik.http.routers.mykeycloak.service=api@internal

    
  
  mysql-cron-backup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - keycloak
      - postgres
    volumes:
      - postgres_data/backup:/backup
    environment:
      - MYSQL_HOST=postgres
      - MYSQL_USER=${POSTGRES_USER}
      - MYSQL_PASS=${POSTGRES_PASSWORD}
      - MAX_BACKUPS=15
      - INIT_BACKUP=0
      # Every day at 03:00
      - CRON_TIME=0 3 * * *
      # Make it small
      - GZIP_LEVEL=9
      # As of MySQL 8.0.21 this is needed
      - MYSQLDUMP_OPTS=--no-tablespaces
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  keycloak_network:
    external: true
  proxy:
    external: true