#!/bin/bash

# Ensure required tools are available
command -v jq >/dev/null 2>&1 || { echo "Error: jq is required but not installed."; exit 1; }

# Set working directory to the location of the script
SERVICE_DIR=$(pwd)
MANIFEST="$SERVICE_DIR/manifest.json"
BASE_COMPOSE="$SERVICE_DIR/compose.base.yml"
TEMPLATE=".env.template"

if [ ! -f "$MANIFEST" ]; then
    echo "Error: manifest.json not found in the current directory."
    exit 1
fi

if [ ! -f "$BASE_COMPOSE" ]; then
    echo "Error: Core config template 'compose.base.yml' is missing."
    exit 1
fi

# 1. Read Metadata
NAME=$(jq -r '.name' "$MANIFEST")
OPTIONS=$(jq -r '.options | keys[]' "$MANIFEST" 2>/dev/null)

echo "=========================================="
echo "  Initializing Installation: $NAME"
echo "=========================================="

# Handle .env initialization
if [ -f "$TEMPLATE" ]; then
    cp "$TEMPLATE" .env
    echo "[Config] Using .env.template as base configuration."
else
    echo "# Automatically generated by homelab installer for $NAME" > .env
fi

declare -A ANSWERS

# 2. Dynamic Prompt Engine
if [ ! -z "$OPTIONS" ]; then
    for opt in $OPTIONS; do
        DESC=$(jq -r ".options.$opt.description" "$MANIFEST")
        TYPE=$(jq -r ".options.$opt.type" "$MANIFEST")

        if [ "$TYPE" == "boolean" ]; then
            read -p "$DESC (y/n): " val
            [[ "$val" =~ ^[Yy]$ ]] && ANSWERS[$opt]="true" || ANSWERS[$opt]="false"
        elif [ "$TYPE" == "select" ]; then
            echo "$DESC"
            select item in $(jq -r ".options.$opt.options[]" "$MANIFEST"); do
                ANSWERS[$opt]=$item
                break
            done
        else
            read -p "$DESC: " val
            ANSWERS[$opt]=$val
        fi

        # Convert option key to UPPERCASE and append to .env
        ENV_KEY=$(echo "$opt" | tr '[:lower:]' '[:upper:]')
        echo "${ENV_KEY}=${ANSWERS[$opt]}" >> .env
    done
fi

# Secure the environment file
chmod 600 .env

# 3. Dynamic Docker Compose Assembly Engine
COMPOSE_ARGS=("-f" "compose.base.yml")

for opt in "${!ANSWERS[@]}"; do
    VAL="${ANSWERS[$opt]}"
    SNIPPET="snippets/${opt}.${VAL}.yml"
    
    if [ -f "$SNIPPET" ]; then
        echo "[Config] Blending override layer: $SNIPPET"
        COMPOSE_ARGS+=("-f" "$SNIPPET")
    fi
done

# 4. Preview and Confirm
echo "--- Final Configuration Preview ---"
docker compose "${COMPOSE_ARGS[@]}" config
echo "=========================================="
read -p "Deploy this configuration? (y/n) " confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    echo "Deployment aborted."
    exit 1
fi

echo "=========================================="
echo "  Launching Container Stack via Docker    "
echo "=========================================="

# Run Docker Compose
docker compose "${COMPOSE_ARGS[@]}" up -d --remove-orphans