#!/bin/bash

# Ensure required tools are available
command -v jq >/dev/null 2>&1 || { echo "Error: jq is required but not installed."; exit 1; }

MANIFEST="manifest.json"
if [ ! -f "$MANIFEST" ]; then
    echo "Error: manifest.json not found in the current directory."
    exit 1
fi

if [ ! -f "compose.base.yml" ]; then
    echo "Error: Core config template 'compose.base.yml' is missing."
    exit 1
fi

# 1. Read Metadata
NAME=$(jq -r '.name' "$MANIFEST")
OPTIONS=$(jq -r '.options | keys[]' "$MANIFEST" 2>/dev/null)

echo "=========================================="
echo "  Initializing Installation: $NAME"
echo "=========================================="
declare -A ANSWERS

# Initialize/clear the local environment file
echo "# Automatically generated by homelab installer for $NAME" > .env

# 2. Dynamic Prompt Engine
if [ ! -z "$OPTIONS" ]; then
    for opt in $OPTIONS; do
        DESC=$(jq -r ".options.$opt.description" "$MANIFEST")
        TYPE=$(jq -r ".options.$opt.type" "$MANIFEST")

        if [ "$TYPE" == "boolean" ]; then
            read -p "$DESC (y/n): " val
            [[ "$val" =~ ^[Yy]$ ]] && ANSWERS[$opt]="true" || ANSWERS[$opt]="false"
        elif [ "$TYPE" == "select" ]; then
            echo "$DESC"
            select item in $(jq -r ".options.$opt.options[]" "$MANIFEST"); do
                ANSWERS[$opt]=$item
                break
            done
        else
            read -p "$DESC: " val
            ANSWERS[$opt]=$val
        fi

        # Convert option key to UPPERCASE for standard environment variable use
        ENV_KEY=$(echo "$opt" | tr '[:lower:]' '[:upper:]')
        echo "${ENV_KEY}=${ANSWERS[$opt]}" >> .env
    done
fi

# 3. Dynamic Docker Compose Assembly Engine
# We build an array of composition flags rather than modifying text files directly
COMPOSE_ARGS=("-f" "compose.base.yml")

for opt in "${!ANSWERS[@]}"; do
    VAL="${ANSWERS[$opt]}"
    
    # Looks for snippets matching the pattern: snippets/option_name.value.yml
    # For example: snippets/use_traefik.true.yml or snippets/database.postgres.yml
    SNIPPET="snippets/${opt}.${VAL}.yml"
    
    if [ -f "$SNIPPET" ]; then
        echo "[Config] Blending override layer: $SNIPPET"
        COMPOSE_ARGS+=("-f" "$SNIPPET")
    fi
done

echo "=========================================="
echo "  Launching Container Stack via Docker    "
echo "=========================================="

# Run Docker Compose utilizing the gathered compilation layers
docker compose "${COMPOSE_ARGS[@]}" up -d --remove-orphans