
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.portainer-http.entrypoints=http"
      - "traefik.http.routers.portainer-http.middlewares=redir-https"
      - "traefik.http.routers.portainer-http.rule=Host(`portainer.linuxpad.blog`)"
      - "traefik.http.routers.portainer-http.service=noop@internal"
      - "traefik.http.routers.portainer-https.entrypoints=https"
      - "traefik.http.routers.portainer-https.tls=true"
      - "traefik.http.routers.portainer-https.middlewares=gzip"
      - "traefik.http.routers.portainer-https.rule=Host(`portainer.linuxpad.blog`)"
      - "traefik.http.services.portainer-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.portainer-backend.loadbalancer.server.port=9443"
      - "traefik.http.routers.portainer-https.middlewares=authelia@docker"

volumes:
  portainer_data:

networks:
  traefik:
    external: true