version: '3'

services:
  portainer:
    image: portainer/portainer-ee:latest # or use community edition via portainer/portainer-ce
    container_name: portainer-ee # may rename to portainer-ce if community edition is used
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- portainer_data:/data
    ports:
      - 9443:9443
    expose:
      - 9443
      - 9000
      - 8000
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.nanaoware.online`) || Host(`www.portainer.nanaoware.online`)
      - traefik.http.services.portainer.loadbalancer.server.port=9443
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.myportainer.middlewares=mywwwredirect
      - traefik.http.routers.myportainer.middlewares=myauth
      - traefik.http.routers.myportainer.service=api@internal

networks:
  proxy:
    external: true
