---
server.host: 0.0.0.0
server.port: 9091
log:
  level: debug

jwt_secret: c50498e29383564cd50bdeda9b74a3bf

default_redirection_url: https://public.nanaoware.online
totp:
  issuer: nanaoware.online

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: public.nanaoware.online
      policy: bypass
    - domain: one-factor.nanaoware.online
      policy: one_factor
    - domain: two-factor.nanaoware.online
      policy: two_factor

session:
  name: authelia_session
  secret: unsecure_session_secret
  expiration: 3600                     # 1 hour
  inactivity: 300                      # 5 minutes
  domain: nanaoware.online         # Should match whatever your root protected domain is

  redis:
    host: authelia-redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: f30ebde68b2c85c1b3fe2d16d9884190
  local:
    path: /data/db.sqlite3

notifier:
  smtp:
    username: apikey
    password: secret
    host: smtp.sendgrid.net
    port: 587
    sender: no-reply@mydomain.com
