---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  nana:
    disabled: false
    displayname: "Nana"
    # Password is akwasi123
    password: "$argon2id$v=19$m=65536,t=3,p=4$umrgBi+cn03iaSZqedcc4g$saG2lv5popbMo2HdvQwDN+bor/GpHZFj/BL7UCIkLaU"  
    email: owarenana06@gmail.com
    groups:
      - admins
      - dev
...