version: '3.9'
services:
    psitransfer:
        image: psitrax/psitransfer
        restart: unless-stopped
        volumes:
            - /srv/appdata/psitransfer/data:/data
        environment:
            - PSITRANSFER_ADMIN_PASS=secret
        ports:
            - 3060:3000
        networks:
            - traefik
       
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik"
            - "traefik.http.routers.psitransfer-http.entrypoints=http"
            - "traefik.http.routers.psitransfer-http.middlewares=redir-https"
            - "traefik.http.routers.psitransfer-http.rule=Host(`psitransfer.linuxpad.blog`)"
            - "traefik.http.routers.psitransfer-http.service=noop@internal"
            - "traefik.http.routers.psitransfer-https.entrypoints=https"
            - "traefik.http.routers.psitransfer-https.tls=true"
            - "traefik.http.routers.psitransfer-https.middlewares=gzip"
            - "traefik.http.routers.psitransfer-https.rule=Host(`psitransfer.linuxpad.blog`)"
            - "traefik.http.services.psitransfer-backend.loadbalancer.server.scheme=http"
            - "traefik.http.services.psitransfer-backend.loadbalancer.server.port=3060"
            - "traefik.http.routers.psitransfer-https.middlewares=authelia@docker"



networks:
  traefik:
    external: true

