version: '3.9'
services:
    psitransfer:
        image: psitrax/psitransfer
        restart: unless-stopped
        volumes:
            - /srv/appdata/psitransfer/data:/data
        environment:
            - PSITRANSFER_ADMIN_PASS=secret
        ports:
            - 3060:3000
        networks:
            - proxy
        labels:
            - traefik.enable=true
            - traefik.http.routers.psitransfer.rule=Host(`psi.nanaoware.online`) || Host(`www.psi.nanaoware.online`)
            - traefik.http.services.psitransfer.loadbalancer.server.port=3060
            - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
            - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
            - traefik.http.routers.mypsitransfer.middlewares=mywwwredirect
            - traefik.http.routers.mypsitransfer.middlewares=myauth
            - traefik.http.routers.mypsitransfer.service=api@internal


networks:
  proxy:
    external: true
