
services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    #network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    networks:
          - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.home-http.entrypoints=http"
      - "traefik.http.routers.home-http.middlewares=redir-https@file"
      - "traefik.http.routers.home-http.rule=Host(`home.linuxpad.blog`)"
      - "traefik.http.routers.home-http.service=noop@internal"
      - "traefik.http.routers.home-https.entrypoints=https"
      - "traefik.http.routers.home-https.tls=true"
      - "traefik.http.routers.home-https.tls.certresolver=le"
      - "traefik.http.routers.home-https.rule=Host(`home.linuxpad.blog`)"
      - "traefik.http.routers.home-https.middlewares=gzip@file,authelia@docker"
      - "traefik.http.routers.home-https.service=home-backend"
      - "traefik.http.services.home-backend.loadbalancer.server.port=8581"


networks:
  traefik:
    external: true