version: '3'
services:

  ghost-server:
    image: ghost:5
    cap_add:
      - CAP_SYS_NICE
    security_opt:
      - seccomp:unconfined
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - ghost-db
    environment:

      url: http://localhost:2368
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: root
      database__connection__password: V3ryS3cretP@ssw0rd
      database__connection__database: ghost
    volumes:
      - /docker/ghost/content:/var/lib/ghost/content
  ghost-db:
    image: mysql:8
    security_opt:
    - seccomp:unconfined
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: V3ryS3cretP@ssw0rd
    volumes:
      - /docker/ghost/mysql:/var/lib/mysql