version: '3'
 
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
 
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
 
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=ghostpassword
    volumes:
      - mariadb-data:/var/lib/mysql
 
  ghost:
    image: ghost:latest
    container_name: ghost
    depends_on:
      - nginx-proxy
      - mariadb
    environment:
      - url=https://tech.nanaoware.online
      - VIRTUAL_HOST=nanaoware.online
      - LETSENCRYPT_HOST=nanaoware.online
      - LETSENCRYPT_EMAIL=owarenana06@gmail.com
      - database__client=mysql
      - database__connection__host=mariadb
      - database__connection__user=ghost
      - database__connection__password=ghostpassword
      - database__connection__database=ghost
    volumes:
      - ghost-data:/var/lib/ghost/content
 
volumes:
  ghost-data:
  mariadb-data:
  certs:
  vhost.d:
  html:
networks:
  default:
    driver: bridge