version: '3.1'

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/ssl:/etc/ssl
    ports:
      - 80:80
      - 443:443

  ghost1:
    image: ghost:latest
    restart: always
    volumes:
      - ./ghost1/content:/var/lib/ghost/content
    environment:
      NODE_ENV: production
      database__client: mysql
      database__connection__host: database_host
      database__connection__user: database_user
      database__connection__password: A_REALLY_LONG_PASSWORD
      database__connection__database: ghost1
      url: https://linux.nanaoware.online     
      
  ghost2:
    image: ghost:latest
    restart: always
    volumes:
      - ./ghost2/content:/var/lib/ghost/content
    environment:
      NODE_ENV: production
      database__client: mysql
      database__connection__host: database_host
      database__connection__user: database_user
      database__connection__password: A_REALLY_LONG_PASSWORD
      database__connection__database: ghost2
      url: https://doc.nanaoware.online       
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: A_REALLY_LONG_PASSWORD
    volumes:
      - ghost-database:/var/lib/mysql
 
volumes:
  ghost-database: