services:
  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      - ./beszel_data:/beszel_data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.entrypoints=http"
      - "traefik.http.routers.beszel.rule=Host(`beszel.linuxpad.blog`)"
      - "traefik.http.middlewares.beszel-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.beszel.middlewares=portainer-https-redirect"
      - "traefik.http.routers.beszel-secure.entrypoints=https"
      - "traefik.http.routers.beszel-secure.rule=Host(`beszel.linuxpad.blog`)"
      - "traefik.http.routers.beszel-secure.tls=true"
      - "traefik.http.routers.beszel-secure.service=beszel"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.portainer-secure.middlewares=authelia@docker"


networks:
  proxy:
    name: proxy
    external: true #do not expose external for security risk
  