services:
  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      - ./beszel_data:/beszel_data
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.mybeszel.rule=Host(`beszel.nanaoware.online`)
      - traefik.http.routers.mybeszel.service=api@internal
      - traefik.http.routers.mybeszel.middlewares=myauth
      - traefik.http.middlewares.myauth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/



networks:
  proxy:
    name: proxy
    external: true #do not expose external for security risk
  