ervices:
  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    
    volumes:
      - ./beszel_data:/beszel_data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.beszel-http.entrypoints=http"
      - "traefik.http.routers.beszel-http.middlewares=redir-https"
      - "traefik.http.routers.beszel-http.rule=Host(`beszel.linuxpad.blog`)"
      - "traefik.http.routers.beszel-http.service=noop@internal"
      - "traefik.http.routers.beszel-https.entrypoints=https"
      - "traefik.http.routers.beszel-https.tls=true"
      - "traefik.http.routers.beszel-https.middlewares=gzip"
      - "traefik.http.routers.beszel-https.rule=Host(`beszel.linuxpad.blog`)"
      - "traefik.http.services.beszel-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.beszel-backend.loadbalancer.server.port=8090"
      - "traefik.http.routers.beszel-https.middlewares=authelia@docker"



networks:
  traefik:
    name: traefik
    external: true #do not expose external for security risk
  
