services:
  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      - ./beszel_data:/beszel_data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.beszel.rule=Host(`beszel.nanaoware.online`)
      - traefik.http.routers.beszel.tls=true
      - traefik.http.routers.beszel.tls.certresolver=prodresolver
      - traefik.http.routers.beszel.entrypoints=websecure
      - traefik.http.services.beszel.loadbalancer.server.port=80
      - traefik.http.routers.beszel.service=beszel
                    #Define midleware 
      - "traefik.http.routers.beszel.middlewares=crowdsec-beszel@docker" 
                    ## Middleware configuration
      - "traefik.http.middlewares.crowdsec-beszel.plugin.crowdsec-bouncer.enabled=true"
      - "traefik.http.middlewares.crowdsec-beszel.plugin.crowdsec-bouncer.crowdseclapikey=uw//V2nuhODeROUjnXQPBSYA7eOFwweLq25s1btEZHc"


networks:
  proxy:
    name: proxy
    external: true #do not expose external for security risk
  