

services:
  app:
    container_name: uptime-kuma
    hostname: uptime-kuma
    image: louislam/uptime-kuma
    restart: always
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/uptimekuma:/app/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.uptime-kuma-http.entrypoints=http"
      - "traefik.http.routers.uptime-kuma-http.middlewares=redir-https"
      - "traefik.http.routers.uptime-kuma-http.rule=Host(`uptime-kuma.linuxpad.blog`)"
      - "traefik.http.routers.uptime-kuma-http.service=noop@internal"
      - "traefik.http.routers.uptime-kuma-https.entrypoints=https"
      - "traefik.http.routers.uptime-kuma-https.tls=true"
      - "traefik.http.routers.uptime-kuma-https.middlewares=gzip"
      - "traefik.http.routers.uptime-kuma-https.rule=Host(`uptime-kuma.linuxpad.blog`)"
      - "traefik.http.services.uptime-kuma-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.uptime-kuma-backend.loadbalancer.server.port=3001"
      - "traefik.http.routers.uptime-kuma-https.middlewares=authelia@docker"


networks:
  traefik:
    external: true



