

services:
  app:
    container_name: uptime-kuma
    hostname: uptime-kuma
    image: louislam/uptime-kuma
    restart: always
    ports:
      - 3001:3001
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/uptimekuma:/app/data
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.myuptime.rule=Host(`uptime.nanaoware.online`)
      - traefik.http.routers.myuptime.service=api@internal
      - traefik.http.routers.myuptime.middlewares=myauth
      - traefik.http.middlewares.myauth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/


networksks:
  proxy:
    external: true