version: "3.8"

services:
  app:
    container_name: uptime-kuma
    hostname: uptime-kuma
    image: louislam/uptime-kuma
    restart: always
    ports:
      - 3001:3001
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/uptimekuma:/app/data
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptimekuma.rule=Host(`uptime.nanaoware.online`) || Host(`www.uptime.nanaoware.online`)
      - traefik.http.services.uptimekuma.loadbalancer.server.port=3001
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.myuptimekuma.middlewares=mywwwredirect
      - traefik.http.routers.myuptimekuma.middlewares=dashboard
      - traefik.http.routers.myuptimekuma.service=api@internal
      - traefik.http.routers.myuptimekuma.tls=true
      - traefik.http.routers.myuptimekuma.tls.certresolver=le
networks:
  proxy:
    external: true