version: '3.8'

services:
  ghost:
    image: ghost:latest
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: ${DB_CLIENT:-mysql}
      database__connection__host: ${DB_HOST:-database}
      database__connection__user: ${DB_USER:-ghost}
      database__connection__password: ${DB_USER_PASS:-DatabasePassword1234}
      database__connection__database: ${DB_NAME:-ghost}
      url: https://linuxpad.blog # adjust to your domain and correct protocol handler + port
      #NODE_ENV: developmnent # default is production already
      mail__transport: "${MAIL_TRANSPORT}"
      mail__options__host: "${MAIL_HOST}"
      mail__options__port: "${MAIL_PORT}"
      mail__options__secureConnection: "${MAIL_SECURE_CONNECTION}"
      mail__options__auth__user: "${MAIL_USER}"
      mail__options__auth__pass: "${MAIL_PASSWORD}"
      security__staffDeviceVerification: false  
    volumes:
      - ghost_content:/var/lib/ghost/content
    networks:
      - ghost_network
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.ghost-http.entrypoints=http"
      - "traefik.http.routers.ghost-http.middlewares=redir-https"
      - "traefik.http.routers.ghost-http.rule=Host(`linuxpad.blog`)"
      - "traefik.http.routers.ghost-http.service=noop@internal"
      - "traefik.http.routers.ghost-https.entrypoints=https"
      - "traefik.http.routers.ghost-https.tls=true"
      - "traefik.http.routers.ghost-https.middlewares=gzip"
      - "traefik.http.routers.ghost-https.rule=Host(`linuxpad.blog`)"
      - "traefik.http.services.ghost-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.ghost-backend.loadbalancer.server.port=2368"
      - "traefik.http.routers.ghost-https.middlewares=authelia@docker"
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-DatabaseRootPassword54321}
      MYSQL_DATABASE: ${DB_NAME:-ghost}
      MYSQL_USER: ${DB_USER:-ghost}
      MYSQL_PASSWORD: ${DB_USER_PASS:-DatabasePassword1234}
    
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/ghost/mysql:/var/lib/mysql
    networks:
      - ghost_network


  ghost-backup:
    image: bennetimo/ghost-backup
    environment:
      DB_CLIENT: mysql
      DB_HOST: db
      DB_USER: ghost
      DB_PASSWORD: ${DB_USER_PASS:-DatabasePassword1234}
      DB_NAME: ghost_db
      BACKUP_INTERVAL: 24h # Daily backups
    volumes:
      - ghost_content:/var/lib/ghost/content:ro # Read-only access to content for backup
      - ./backups:/backups # Store backups here
    depends_on:
      - db

volumes:
  ghost_content:
  db_data:

networks:
  ghost_network:
  traefik:
    external: true # If Traefik is in a separate docker-compose file