networks:
  ghost-network:
    external: true
  traefik:
    external: true

volumes:
  mysql-data:
  ghost-data:
  ghost-mysql-backup:
  ghost-data-backups:
  ghost-database-backups:

services:
  mysql:
    image: ${GHOST_MYSQL_IMAGE_TAG}
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${GHOST_DB_NAME}
      MYSQL_USER: ${GHOST_DB_USER}
      MYSQL_PASSWORD: ${GHOST_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${GHOST_DB_ADMIN_PASSWORD}
    networks:
      - ghost-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  ghost:
    image: ${GHOST_IMAGE_TAG}
    volumes:
      - ghost-data:${DATA_PATH}
    environment:
      NODE_ENV: production
      url: ${GHOST_URL}
      database__client: mysql
      database__connection__host: mysql
      database__connection__database: ${GHOST_DB_NAME}
      database__connection__user: ${GHOST_DB_USER}
      database__connection__password: ${GHOST_DB_PASSWORD}
    networks:
      - ghost-network
      - traefik
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/2368' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.ghost-http.entrypoints=http"
      - "traefik.http.routers.ghost-http.middlewares=redir-https"
      - "traefik.http.routers.ghost-http.rule=Host(`linuxpad.blog`)"
      - "traefik.http.routers.ghost-http.service=noop@internal"
      - "traefik.http.routers.ghost-https.entrypoints=https"
      - "traefik.http.routers.ghost-https.tls=true"
      - "traefik.http.routers.ghost-https.middlewares=gzip"
      - "traefik.http.routers.ghost-https.rule=Host(`linuxpad.blog`)"
      - "traefik.http.services.ghost-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.ghost-backend.loadbalancer.server.port=2368"
      - "traefik.http.routers.ghost-https.middlewares=authelia@docker"
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      traefik:
        condition: service_healthy

  backups:
    image: ${GHOST_MYSQL_IMAGE_TAG}
    command: >-
      sh -c 'sleep $BACKUP_INIT_SLEEP &&
      while true; do
        mysqldump -h mysql -u $GHOST_DB_USER -p"$GHOST_DB_PASSWORD" $GHOST_DB_NAME | gzip > "$MYSQL_BACKUPS_PATH/$MYSQL_BACKUP_NAME-$(date '+%Y-%m-%d_%H-%M').gz" &&
        tar -zcpf $DATA_BACKUPS_PATH/$DATA_BACKUP_NAME-$(date "+%Y-%m-%d_%H-%M").tar.gz $DATA_PATH &&
        find $MYSQL_BACKUPS_PATH -type f -mtime +$MYSQL_BACKUP_PRUNE_DAYS | xargs rm -f &&
        find $DATA_BACKUPS_PATH -type f -mtime +$DATA_BACKUP_PRUNE_DAYS | xargs rm -f;
        sleep $BACKUP_INTERVAL; done'
    volumes:
      - ghost-mysql-backup:/var/lib/mysql
      - ghost-data:${DATA_PATH}
      - ghost-data-backups:${DATA_BACKUPS_PATH}
      - ghost-database-backups:${MYSQL_BACKUPS_PATH}
    environment:
      GHOST_DB_NAME: ${GHOST_DB_NAME}
      GHOST_DB_USER: ${GHOST_DB_USER}
      GHOST_DB_PASSWORD: ${GHOST_DB_PASSWORD}
      BACKUP_INIT_SLEEP: ${BACKUP_INIT_SLEEP}
      BACKUP_INTERVAL: ${BACKUP_INTERVAL}
      MYSQL_BACKUP_PRUNE_DAYS: ${MYSQL_BACKUP_PRUNE_DAYS}
      DATA_BACKUP_PRUNE_DAYS: ${DATA_BACKUP_PRUNE_DAYS}
      MYSQL_BACKUPS_PATH: ${MYSQL_BACKUPS_PATH}
      DATA_BACKUPS_PATH: ${DATA_BACKUPS_PATH}
      DATA_PATH: ${DATA_PATH}
      MYSQL_BACKUP_NAME: ${MYSQL_BACKUP_NAME}
      DATA_BACKUP_NAME: ${DATA_BACKUP_NAME}
    networks:
      - ghost-network
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy