

services:

  server:
    image: peterdavehello/tor-socks-proxy:latest
    container_name: tor_server
    dns:
      - 1.1.1.1
      - 8.8.4.4
      - 8.8.8.8
    healthcheck:
      test: ["CMD-SHELL","echo", "1"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - tor
    restart: unless-stopped
    volumes:
      - server_config:/etc/tor
      - server_data:/var/lib/tor
      - /etc/localtime:/etc/localtime:ro

networks:
  tor:
    external: true

volumes:
  server_config:
    driver: local
  server_data:
    driver: local