version: "3.9"

services:
  minio-s3:
    image: bitnami/minio:2023
    container_name: minio
    hostname: minio
    environment:
      - MINIO_ROOT_USER=minio # change this
      - MINIO_ROOT_PASSWORD=akosua123 # change this
    ports:
      - 9001:9001/tcp
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/minio/data:/data
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.rule=Host(`minio.nanaoware.online`) || Host(`www.minio.nanaoware.online`)
      - traefik.http.services.minio.loadbalancer.server.port=9001
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.myminio.middlewares=mywwwredirect
      - traefik.http.routers.myminio.middlewares=dashboard
      - traefik.http.routers.myminio.service=api@internal
      - traefik.http.routers.myminio.tls=true
      - traefik.http.routers.myminio.tls.certresolver=le

networks:
  proxy:
    external: true