version: "3.8"

services:
  excalidraw:
    container_name: excalidraw
    image: excalidraw/excalidraw:latest
    ports:
      - "3030:80"
    restart: unless-stopped
    stdin_open: true
    healthcheck:
      disable: true
    environment:
      - NODE_ENV=production
    networks:
      - web
    volumes:
      - ./:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./yarn.lock:/opt/node_app/yarn.lock
      - notused:/opt/node_app/app/node_modules
    labels:
      - traefik.enable=true
      - traefik.http.routers.excalidraw.rule=Host(`draw.example.com`)
      - traefik.http.routers.excalidraw.tls=true
      - traefik.http.routers.excalidraw.tls.certResolver=lets-encrypt
      - traefik.http.services.excalidraw.loadbalancer.server.port=80
      - traefik.docker.network=web
    #  # Part for local lan services only; disable to expose externally
      - traefik.http.routers.excalidraw.middlewares=simpleAuth@file

networks:
  web:
   external: true
