services:
  keepassxc:
    image: lscr.io/linuxserver/keepassxc:latest
    container_name: keepassxc
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/appdata/keepassxc/config:/config
    ports:
      - 3004:3000
      - 3005:3001
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.keepassxc.rule=Host(`keepassxc.nanaoware.online`) || Host(`www.keepassxc.nanaoware.online`)
      - traefik.http.services.keepassxc.loadbalancer.server.port=3004
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.mykeepassxc.middlewares=mywwwredirect
      - traefik.http.routers.mykeepassxc.middlewares=myauth
      - traefik.http.routers.mykeepassxc.service=api@internal

networks:
  proxy:
    external: true

