services:
  keepassxc:
    image: lscr.io/linuxserver/keepassxc:latest
    container_name: keepassxc
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/appdata/keepassxc/config:/config
    ports:
      - 3004:3000
      - 3005:3001
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.keepassxc.rule=Host(`keepassxc.nanaoware.online`)
      - traefik.http.routers.keepassxc.entrypoints=websecure
      - traefik.http.routers.keepassxc.tls=true
      - traefik.http.routers.keepassxc.tls.certResolver=lets-encrypt
      - traefik.http.services.keepassxc.loadbalancer.server.port=3005
    #  # Optional part for file upload max sizes
      - traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=50000000
      - traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=50000000
      - traefik.http.middlewares.limit.buffering.memRequestBodyBytes=50000000
      - traefik.http.middlewares.limit.buffering.memResponseBodyBytes=50000000
    #  # Optional part for traefik middlewares
      - traefik.http.routers.codeserver.middlewares=simpleAuth@file

networks:
  web:
    external: true

