services:
  nautical-backup:
    image: minituff/nautical-backup:2.11
    container_name: nautical-backup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /config:/config
      - /source:/app/source
    ports:
      - "8069:8069/tcp"
    environment: # Optional variables
      - TZ=America/Los_Angeles
      - CRON_SCHEDULE=0 4 * * *
      - SKIP_CONTAINERS=example1,example2,example3
      - SKIP_STOPPING=example1,example2
      - BACKUP_ON_START=true
      - LOG_LEVEL=INFO
      - REQUIRE_LABEL=true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.nautical-http.entrypoints=http"
      - "traefik.http.routers.nautical-http.middlewares=redir-https"
      - "traefik.http.routers.nautical-http.rule=Host(`nautical.linuxpad.blog`)"
      - "traefik.http.routers.nautical-http.service=noop@internal"
      - "traefik.http.routers.nautical-https.entrypoints=https"
      - "traefik.http.routers.nautical-https.tls=true"
      - "traefik.http.routers.nautical-https.middlewares=gzip"
      - "traefik.http.routers.nautical-https.rule=Host(`nautical.linuxpad.blog`)"
      - "traefik.http.services.nautical-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.nautical-backend.loadbalancer.server.port=8069"
      - "traefik.http.routers.nautical-https.middlewares=authelia@docker"
      

networks:
  traefik:
    external: true