services:
  nautical-backup:
    image: minituff/nautical-backup:2.11
    container_name: nautical-backup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/nana/nautical_backup/app/source:/app/source
      - /home/nana/nautical_backup/app/destination:/app/destination
        # Alternative destination directories examples
      - /mnt/docker-volumes/ghost:/app/source/ghost
      - /home/nana/portainer/portainer-data:/app/source/portainer
      - /home/nana/traefik:/app/source/traefik
      - /home/nana/dozzle:/app/source/dozzle
      - /home/nana/cronicle:/app/source/cronicle
      - /home/nana/uptime:/app/source/uptime
      - /home/nana/flare:/app/source/flare
      - /home/nana/gotify:/app/source/gotify
      - /home/nana/hoarder:/app/source/hoarder
      - /home/nana/vault:/app/source/vault
      - /home/nana/watchtower:/app/source/watchtower
      - /home/nana/it-tools:/app/source/it-tools
      - /home/nana/authelia:/app/source/authelia

    ports:
      - "8069:8069/tcp"
    environment: # Optional variables
      - TZ=America/Los_Angeles
      - CRON_SCHEDULE=0 4 * * *
     # - SKIP_CONTAINERS=example1,example2,example3
     # - SKIP_STOPPING=example1,example2
      - BACKUP_ON_START=true
      - LOG_LEVEL=INFO
      - REQUIRE_LABEL=false
      - HTTP_REST_API_USERNAME=admin
      - HTTP_REST_API_PASSWORD=password
      - ADDITIONAL_FOLDERS=/home/nana/.config
      - ADDITIONAL_FOLDERS_WHEN=before

networks:
  traefik:
    external: true