services:
  nautical-backup:
    image: minituff/nautical-backup:2.11
    container_name: nautical-backup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/nana/nautical_backup/app/source:/app/source
      - /home/nana/nautical_backup/app/destination:/app/destination
      - /home/nana:/app/source/nana
        # Alternative destination directories examples
      - /mnt/docker-volumes/uptimekuma:/app/source/uptimekuma
      - /mnt/docker-volumes/ghost:/app/source/ghost
      - /home/nana/portiner/portainer-data:/app/source/portainer

    ports:
      - "8069:8069/tcp"
    environment: # Optional variables
      - TZ=America/Los_Angeles
      - CRON_SCHEDULE=0 4 * * *
     # - SKIP_CONTAINERS=example1,example2,example3
     # - SKIP_STOPPING=example1,example2
      - BACKUP_ON_START=true
      - LOG_LEVEL=INFO
      - REQUIRE_LABEL=false
      - HTTP_REST_API_USERNAME=admin
      - HTTP_REST_API_PASSWORD=password
      - ADDITIONAL_FOLDERS=/home/nana/
      - ADDITIONAL_FOLDERS_WHEN=before

networks:
  traefik:
    external: true