################################################################################
# HOMELAB
################################################################################

include:
    #############################################################################
    # TRAEFIK (CORE)
    #############################################################################

    - apps/traefik.yaml # Traefik (Reverse Proxy)
    - apps/socket-proxy.yaml # Docker Socket Proxy (Security)
    - apps/deunhealth.yaml # Restart Unhealthy Containers
    - apps/fail2ban.yaml
    #############################################################################
    # MEDIA
    #############################################################################

    - apps/homepage/homepage.yaml # Heomepage(Landing Page)
   # - apps/ghost/ghost.yaml # Blog (CMS Server)
   # - apps/wordpress/wordpress.yaml # Blog (CMS Server)
   # - apps/immich/immich.yaml # Photos(Backup)
    - apps/vault.yaml # Password Manager(Vault)
    - apps/nextcloud.yaml # Backup(Media Backup)
    - apps/portainer.yaml # Docker Mgt(Docker)
    - apps/beszel.yaml # Docker Monitoring(Docker)
    - apps//dozzle/dozzle.yaml # Log(Docker Log)
   # - apps/authentic/authentic.yaml # Authentication(Authenticator)
    - apps/link.yaml # Link(LinkTree Alt.)
    - apps/nextterm.yaml # Termninal (Emulator)
    # - apps/calibre-web.yaml # Calibre Web-UI

    #############################################################################
    # UTILITIES
    #############################################################################

    - apps/watchtower/watchtower.yaml #  Watchtower (Container Updating)
    - apps/umami.yaml # Analytics (Web Analytics)
    - apps/paperless.yaml # Storage (File Management)
    - apps/uptime.yaml # Up Time (Server Uptime)
    # - apps/portainer.yaml # Portainer (Container Management)

    #############################################################################
    # MISCELLANEOUS
    #
    # * Note the existing services that are disabled by default.
    #############################################################################

    # - apps/chat-gpt-next-web.yaml # ChatGPT Next Web
    # - apps/chatgpt-in-slack.yaml # ChatGPT Slack Bot
    # - apps/libreoffice.yaml # LibreOffice (Office Suite)
    # - apps/umami.yaml # Umami Analytics
    # - apps/homeassistant/docker-compose.yaml # Home Assistant (Smart Home)
    # - apps/healthchecks.yaml # Healthchecks (Monitoring)

################################################################################
# NETWORK CONFIGURATION
################################################################################

networks:
    proxy:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.12.0/24
    docker:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.13.0/24
    internal:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.14.0/24