
version: "3.0"
services:
  littlelink-server:
    image: ghcr.io/techno-tim/littlelink-server:latest
    profiles: [ "media", "all"]

    # dockerhub is also supported timothystewart6/littlelink-server
    # image: timothystewart6/littlelink-server:latest
    container_name: littlelink-server
    environment:
      - META_TITLE=Dennis Agyepong
      - META_DESCRIPTION=Cyber Security | Gamer | Linux Enthusiast | Homelab | 🇺🇸 🇬🇭   | FOSS ADVOCATE
      - META_AUTHOR=Dennis Agyepong
      - META_KEYWORDS=HomeLab, Python, Docker, Engineering
      - LANG=en
      - META_INDEX_STATUS=all
      - OG_SITE_NAME=Dennis Agyepong
      - OG_TITLE=Dennis Agyepong
      - OG_DESCRIPTION=The home of Dennis Agyepong
      - OG_URL=https://linuxpad.blog
      - OG_IMAGE=https://pfp.nostr.build/663ce288381c6a1bbf9ee09cccdf8efcc5025ded44e22e50a041543cd4f8f82c.jpg
      - OG_IMAGE_WIDTH=400
      - OG_IMAGE_HEIGHT=400
      - GA_TRACKING_ID=G-XXXXXXXXXX
      - THEME=Dark
      - FAVICON_URL=https://pfp.nostr.build/663ce288381c6a1bbf9ee09cccdf8efcc5025ded44e22e50a041543cd4f8f82c.jpg
      - AVATAR_URL=https://pfp.nostr.build/663ce288381c6a1bbf9ee09cccdf8efcc5025ded44e22e50a041543cd4f8f82c.jpg
      - AVATAR_2X_URL=https://pfp.nostr.build/663ce288381c6a1bbf9ee09cccdf8efcc5025ded44e22e50a041543cd4f8f82c.jpg
      - AVATAR_ALT=Dennis AgyepongProfile Pic
      - NAME=Dennis Agyepong
      - BIO=Cyber-Security Analyst | Gamer | Tech Hobbyist | Linux Enthusiast | Homelab | 🇺🇸 🇬🇭 | FOSS ADVOCATE
      # use ENV variable names for order, listed buttons will be boosted to the top
      - BUTTON_ORDER=REDDIT,GITHUB,GITLAB,WORDPRESS,GHOST,INSTAGRAM,LINKED_IN,DISCORD,FACEBOOK,TIKTOK,PATREON,GEAR,DOCUMENTATION
      # you can render an unlimited amount of custom buttons by adding 
      # the CUSTOM_BUTTON_* variables and by using a comma as a separator.
      - CUSTOM_BUTTON_TEXT=Documentation,Homelab
      - CUSTOM_BUTTON_URL=https://doc.nanaoware.online
      - CUSTOM_BUTTON_COLOR=#000000,#000000
      - CUSTOM_BUTTON_TEXT_COLOR=#ffffff,#ffffff
      - CUSTOM_BUTTON_ALT_TEXT=Homelab documentation site
      - CUSTOM_BUTTON_NAME=DOCUMENTATION,GEAR
      - CUSTOM_BUTTON_ICON=fas file-alt,fas fa-cog
      - GITHUB=https://github.com/dagyepong
      - GITLAB=https://gitlab.com/na204
      - WORDPRESS=https://tech.nanaoware.online
      - GHOST=https://linuxpad.blog
      - TWITTER=https://twitter.com/
      - INSTAGRAM=https://instagram.com/oware84?igsh=cjhxOXZwanRiMmhj
      - REDDIT=https://www.reddit.com/user/nanaoware/
      - LINKED_IN=https://www.linkedin.com/in/nana-oware-944bba282/
      #- YOUTUBE=https://youtube.com
      #- TWITCH=https://twich.com
      - DISCORD=https://discord.com/nana12
      - TIKTOK=https://tiktok.com/@nanaoware
      - GHOST=https://linuxpad.blog
      - FACEBOOK=https://www.facebook.com/profile.php?id=100094076774707&mibextid=ZbWKwL
      - PATREON=https://patreon.com/Linuxpad?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=creatorshare_creator&utm_content=join_link
      - FOOTER=Linuxpad © 2024
    ports:
      - 8080:3000


    labels:
      - traefik.enable=true
      - traefik.http.routers.littlelink.rule=Host(`link.nanaoware.online`) || Host(`www.link.nanaoware.online`)
      - traefik.http.services.littlelink.loadbalancer.server.port=8081
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.mylittlelink.middlewares=mywwwredirect
      - traefik.http.routers.mylittlelink.middlewares=dashboard
      - traefik.http.routers.mylittlelink.service=api@internal
      - traefik.http.routers.mylittlelink.tls=true
      - traefik.http.routers.mylittlelink.tls.certresolver=le

    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
