

services:
  portainer:
    image: portainer/portainer-ee:latest # or use community edition via portainer/portainer-ce
    container_name: portainer-ce # may rename to portainer-ce if community edition is used
    restart: unless-stopped
    profiles: [ "media", "all"]

    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- /var/run/docker.sock:/var/run/docker.sock:ro
      #- portainer_data:/data
    #command: -H unix:///var/run/docker.sock # # Use Docker Socket Proxy instead for improved security
    command: -H tcp://socket-proxy:2375
    environment:
      #- TZ: ${TZ}
      - DOCKER_HOST: tcp://socket-proxy:2375
    ports:
      - 9443:9443
    networks:
      - proxy
      - docker
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.nanaoware.online`) || Host(`www.portainer.nanaoware.online`)
      - traefik.http.services.portainer.loadbalancer.server.port=9443
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.myportainer.middlewares=mywwwredirect
      - traefik.http.routers.myportainer.middlewares=dashboard
      - traefik.http.routers.myportainer.service=api@internal
      - traefik.http.routers.mypotrtainer.tls=true
      - traefik.http.routers.myportainer.tls.certresolver=le

