name: my-wireguard-project
services:
    amnezia-wg-easy:
        container_name: amnezia-wg-easy
        environment:
            - LANG=en
            - WG_HOST=192.168.1.140
            - PASSWORD_HASH=$2a$12$qIqztWwjTh3B.ovxjjwRueveyPHQgje3daiwZuO1Qnv0tbqZHhpbS
            - PORT=51821
            - WG_PORT=51820
        volumes:
            - ~/.amnezia-wg-easy:/etc/wireguard
            - /lib/modules:/lib/modules:ro
        ports:
            - 51820:51820/udp
            - 51821:51821/tcp
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
            - net.ipv4.ip_forward=1
        devices:
            - /dev/net/tun:/dev/net/tun
        restart: unless-stopped
        image: ghcr.io/w0rng/amnezia-wg-easy