services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    networks:
      - traefik
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.wg-easy-http.entrypoints=http"
      - "traefik.http.routers.wg-easy-http.middlewares=redir-https"
      - "traefik.http.routers.wg-easy-http.rule=Host(`wg-easy.linuxpad.blog`)"
      - "traefik.http.routers.wg-easy-http.service=noop@internal"
      - "traefik.http.routers.wg-easy-https.entrypoints=https"
      - "traefik.http.routers.wg-easy-https.tls=true"
      - "traefik.http.routers.wg-easy-https.middlewares=gzip"
      - "traefik.http.routers.wg-easy-https.rule=Host(`wg-easy.linuxpad.blog`)"
      - "traefik.http.services.wg-easy-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.wg-easy-backend.loadbalancer.server.port=51821"
      - "traefik.http.routers.wg-easy-https.middlewares=authelia@docker"


networks:
  traefik:
    external: true

