services:
  amnezia-wg-easy:
    image: ghcr.io/deckersu/amnezia-wg-easy:latest
    container_name: amnezia-wg-easy
    environment:
      # Required: your server's IP or domain
      - WG_HOST=192.168.1.141
      # Authentication (use bcrypt hash or plain password; the image supports plain)
      - PASSWORD=your_secure_password   # change this!
      # Ports
      - PORT=51821
      - WG_PORT=51820
      # DNS
      - WG_DEFAULT_DNS=1.1.1.1
      # CRITICAL: Add S3 and S4 set to 0
      - S3=0
      - S4=0
      # Optional Amnezia junk parameters (you can adjust)
      - JC=4
      - JMIN=40
      - JMAX=70
      # H1-H4 are usually fixed, but you can set them if needed
      - H1=1
      - H2=2
      - H3=3
      - H4=4
    volumes:
      - ./amnezia-wg-easy:/etc/amnezia/amneziawg   # note the path
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    devices:
      - /dev/net/tun:/dev/net/tun