
services:
  speedtest:
    container_name: speedtest-tracker
    image: henrywhitaker3/speedtest-tracker:latest
    restart: unless-stopped
    volumes:
      - ./config:/config
    networks:
      - traefik
    environment:
      - TZ=Europe/Zurich
      - PUID=1026
      - PGID=100
      - OOKLA_EULA_GDPR=true
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 200k
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.speed-http.entrypoints=http"
      - "traefik.http.routers.speed-http.middlewares=redir-https@file"
      - "traefik.http.routers.speed-http.rule=Host(`speed.linuxpad.blog`)"
      - "traefik.http.routers.speed-http.service=noop@internal"
      - "traefik.http.routers.speed-https.entrypoints=https"
      - "traefik.http.routers.speed-https.tls=true"
      - "traefik.http.routers.speed-https.tls.certresolver=le"
      - "traefik.http.routers.speed-https.rule=Host(`speed.linuxpad.blog`)"
      - "traefik.http.routers.speed-https.middlewares=gzip@file,authelia@docker"
      - "traefik.http.routers.speed-https.service=speed-backend"
      - "traefik.http.services.speed-backend.loadbalancer.server.port=3021"


networks:
  traefik:
    external: true
