---
version: "3"
services:
  little-link:
    image: docker.io/hikariai/littlelink-server:latest
    container_name: littlelink-server
    environment:
      - META_TITLE=Nana Oware
      - META_DESCRIPTION=Nana Oware Link page
      - META_AUTHOR=Nana Owrae
      - THEME=Dark
      - FAVICON_URL=https://nrmjjlvckvsb.compat.objectstorage.ap-tokyo-1.oraclecloud.com/picgo/2022/10-22-0cdf62d6ef43f5c3ad43827c749f5cdd.jpg
      - AVATAR_URL=https://nrmjjlvckvsb.compat.objectstorage.ap-tokyo-1.oraclecloud.com/picgo/2022/10-22-0cdf62d6ef43f5c3ad43827c749f5cdd.jpg
      - AVATAR_2X_URL=https://nrmjjlvckvsb.compat.objectstorage.ap-tokyo-1.oraclecloud.com/picgo/2022/10-22-0cdf62d6ef43f5c3ad43827c749f5cdd.jpg
      - AVATAR_ALT=Nana Oware Profile Pic
      - NAME=Nana Oware
      - BIO=Hey! Just a place where you can connect with me!
      - BLOG=https://blog.nanaoware.online
      - GITHUB=https://github.com/dagyepong/Home-lab/tree/main
      - DISCORD=https://discord.gg/nana12
      - TWITCH=https://www.twitch.tv/
      - TELEGRAM=https://t.me/
      - FOOTER=Thanks for stopping by!
      - EMAIL=nanaoware06@gmail.com
      # - LINKED_IN=
      # - TWITTER=
      # - INSTAGRAM=
      # - YOUTUBE=
      # - TIKTOK=
      # - KIT=
      # - SPOTIFY=https://www.spotify.com/
      # - REDDIT=https://www.reddit.com/
      # - MEDIUM=https://medium.com
      # - PINTEREST=https://www.pinterest.com/
      # - SOUND_CLOUD=https://souncloud.com
      # - FIGMA=https://figma.com
      # - TUMBLR=https://www.tumblr.com/
      # - STEAM=https://steamcommunity.com/
      # - VIMEO=https://vimeo.com/
      # - GOODREADS=https://www.goodreads.com/
      # - SKOOB=https://www.skoob.com.br/
    ports:
      - 3030:3000
    restart: always
    security_opt:
      - no-new-privileges:true