version: '3.8'

services:
    app:
        image: kaangiray26/forte:4.3
        container_name: forte
        restart: on-failure
        ports:
            - 3000:3000
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            port: 3000               # Set Port
            version: "4.3"           # Set Version
            verbose: false           # Verbose Logging
            custom_about: false      # For your own about page
            hostname: localhost      # Set Hostname
            NODE_ENV: production     # Set Node Environment
            POSTGRES_HOST: postgres  # Postgres Host/IP
            POSTGRES_USER: forte     # Set Postgres Username
            POSTGRES_PASSWORD: forte # Set Postgres Password
            POSTGRES_PORT: 5432      # Postgres Database Port
            POSTGRES_DB: forte       # Set Postgres Database Name
        volumes:
            - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/forte/library:/library # your music library to import from
        networks:
            - proxy
        labels:
            - traefik.enable=true
            - traefik.http.routers.forte.rule=Host(`forte.nanaoware.online`) || Host(`www.forte.nanaoware.online`)
            - traefik.http.services.forte.loadbalancer.server.port=3000
            - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
            - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
            - traefik.http.routers.myforte.middlewares=mywwwredirect
            - traefik.http.routers.myforte.middlewares=myauth
            - traefik.http.routers.myforte.service=api@internal

    postgres:
        image: kaangiray26/postgres:2.0
        container_name: forte-db
        restart: always
        environment:
            POSTGRES_DB: forte       # Set Postgres Database Name
            POSTGRES_USER: forte     # Set Postgres Username
            POSTGRES_PASSWORD: forte # Set Postgres Password
        volumes:
            - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/forte/db:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U forte" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - proxy

networks:
   proxy:
     external: true

## username forte & alternative as password
