version: '3.9'
services:
  slink:
    image: anirdev/slink:latest
    container_name: slink
    environment:
      - ORIGIN=https://mondomaine.com
      - USER_APPROVAL_REQUIRED=false
      - STORAGE_PROVIDER=local
      #- STORAGE_PROVIDER=smb
      #- SMB_HOSTSMB_HOST=
      #- SMB_USERNAME=
      #- SMB_PASSWORD=
      #- SMB_SHARE=
    volumes:
      - /srv/appdata/slink/var/data:/app/var/data
      - /srv/appdata/slink/images:/app/slink/images
    ports:
      - "3010:3000"
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.slink.rule=Host(`slink.nanaoware.online`) || Host(`www.slink.nanaoware.online`)
      - traefik.http.services.slink.loadbalancer.server.port=3010
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.myslink.middlewares=mywwwredirect
      - traefik.http.routers.myslink.middlewares=dashboard
      - traefik.http.routers.myslink.service=api@internal
      - traefik.http.routers.myslink.tls=true
      - traefik.http.routers.myslink.tls.certresolver=le

networks:
  proxy:
    external: true
