
services:
  # Dockge - Docker Compose Manager
  dockge:
    image: louislam/dockge
    container_name: dockge
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "5005:5001"
    networks:
      - proxy
      - socket
    volumes:
      - ./data:/app/data
      - /opt/stacks:/opt/stacks
    environment:
      #- DOCKGE_STACKS_DIR=/opt/stacks
      - DOCKER_HOST=tcp://socketproxy:2375
    labels:
      - traefik.enable=true
      - traefik.http.routers.dockge.rule=Host(`dockge.nanaoware.online`) || Host(`www.dockge.nanaoware.online`)
      - traefik.http.services.dockge.loadbalancer.server.port=5005
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.mydockge.middlewares=mywwwredirect
      - traefik.http.routers.mydockge.middlewares=myauth
      - traefik.http.routers.mydockge.service=api@internal

networks:
  proxy:
    name: proxy
    external: true #do not expose external for security risk
  socket:
    name: socket