
version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /opt/stacks:/opt/stacks
    
    networks:
      - proxy
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/opt/stacks
    labels:
      - traefik.enable=true
      - traefik.http.routers.dockge.rule=Host(`dockge.nanaoware.online`) || Host(`www.dockge.nanaoware.online`)
      - traefik.http.services.dockge.loadbalancer.server.port=5005
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.mydockge.middlewares=mywwwredirect
      - traefik.http.routers.mydockge.middlewares=dashboard
      - traefik.http.routers.mydockge.service=api@internal
      - traefik.http.routers.mydockge.tls=true
      - traefik.http.routers.mydockge.tls.certresolver=le

networks:
  proxy:
    name: proxy
    external: true #do not expose external for security risk